export type FoodTag =
  | 'starch' | 'protein' | 'veggie' | 'fruit' | 'fat' | 'dairy'
  | 'meal' | 'junk' | 'coffee' | 'condiment' | 'softdrink' | 'beverage' | 'alcohol';

export interface FoodItem {
  name: string;
  nameEn?: string;
  calories: number; // per 100g
  protein: number;  // per 100g
  fat: number;      // per 100g
  carbs: number;    // per 100g
  fiber?: number;   // per 100g
  tag: FoodTag;
}

// Auto-generated from VTN_FCT_2007.pdf — 526 foods
export const FOODS: FoodItem[] = [
  { name: 'Gạo nếp cái', nameEn: 'Glutinous rice, milled', calories: 344, protein: 8.61, fat: 1.51, carbs: 74.51, tag: 'starch' },
  { name: 'Cà phê đen đá (ko đường)', nameEn: 'Vietnamese Black Iced Coffee (No Sugar)', calories: 5, protein: 0.4, fat: 0.1, carbs: 0.8, tag: 'coffee' },
  { name: 'Bánh phở tươi', nameEn: 'Fresh rice noodle strands', calories: 143, protein: 3.2, fat: 0.4, carbs: 31.7, tag: 'starch' },
  { name: 'Bánh phở khô', nameEn: 'Dried rice noodle strands', calories: 348, protein: 7.0, fat: 0.5, carbs: 78.8, tag: 'starch' },
  { name: 'Bún tươi', nameEn: 'Fresh rice vermicelli', calories: 110, protein: 1.7, fat: 0.1, carbs: 25.7, tag: 'starch' },
  { name: 'Bún khô', nameEn: 'Dried rice vermicelli', calories: 352, protein: 7.2, fat: 0.4, carbs: 79.9, tag: 'starch' },
  { name: 'Bánh đa đỏ (Hải Phòng)', nameEn: 'Haiphong brown flat rice noodles', calories: 320, protein: 6.2, fat: 0.4, carbs: 72.8, tag: 'starch' },
  { name: 'Rau tía tô', nameEn: 'Perilla leaves', calories: 25, protein: 2.9, fat: 0.4, carbs: 3.4, fiber: 2.2, tag: 'veggie' },
  { name: 'Rau kinh giới', nameEn: 'Vietnamese balm leaves', calories: 22, protein: 2.7, fat: 0.3, carbs: 2.8, fiber: 2.0, tag: 'veggie' },
  { name: 'Rau ngổ (Rau ngổ ôm)', nameEn: 'Rice paddy herb', calories: 15, protein: 1.5, fat: 0.1, carbs: 2.3, fiber: 2.1, tag: 'veggie' },
  { name: 'Rau húng láng (Húng thơm)', nameEn: 'Mint leaves láng variety', calories: 18, protein: 2.0, fat: 0.2, carbs: 2.4, fiber: 2.0, tag: 'veggie' },
  { name: 'Húng quế (Húng chó)', nameEn: 'Thai basil', calories: 23, protein: 3.2, fat: 0.6, carbs: 2.7, fiber: 1.6, tag: 'veggie' },
  { name: 'Húng lủi (Húng nhủi)', nameEn: 'Spearmint', calories: 44, protein: 3.3, fat: 0.7, carbs: 8.4, fiber: 6.8, tag: 'veggie' },
  { name: 'Rau răm', nameEn: 'Vietnamese coriander', calories: 30, protein: 4.7, fat: 0.5, carbs: 2.8, fiber: 2.5, tag: 'veggie' },
  { name: 'Mùi tàu (Ngò gai)', nameEn: 'Culantro / Sawtooth coriander', calories: 25, protein: 2.1, fat: 0.3, carbs: 2.4, fiber: 2.8, tag: 'veggie' },
  { name: 'Mùi ta (Ngò rí)', nameEn: 'Coriander / Cilantro', calories: 23, protein: 2.1, fat: 0.5, carbs: 3.7, fiber: 2.8, tag: 'veggie' },
  { name: 'Thì là', nameEn: 'Dill', calories: 43, protein: 3.5, fat: 1.1, carbs: 7.0, fiber: 2.1, tag: 'veggie' },
  { name: 'Rau khoai lang', nameEn: 'Sweet potato leaves', calories: 22, protein: 2.2, fat: 0.2, carbs: 2.8, fiber: 2.0, tag: 'veggie' },
  { name: 'Rau ngót (Bồ ngót)', nameEn: 'Katuk / Star gooseberry leaves', calories: 35, protein: 5.3, fat: 0.4, carbs: 3.4, fiber: 2.5, tag: 'veggie' },
  { name: 'Rau bí (Ngọn bí ngô)', nameEn: 'Pumpkin tendrils / Pumpkin leaves', calories: 18, protein: 2.5, fat: 0.2, carbs: 2.3, fiber: 2.1, tag: 'veggie' },
  { name: 'Rau dền gai', nameEn: 'Spiny amaranth', calories: 24, protein: 3.1, fat: 0.3, carbs: 2.1, fiber: 1.8, tag: 'veggie' },
  { name: 'Rau cải xoong', nameEn: 'Watercress', calories: 11, protein: 2.3, fat: 0.1, carbs: 1.3, fiber: 0.5, tag: 'veggie' },
  { name: 'Hoa chuối bào', nameEn: 'Shredded banana blossom', calories: 23, protein: 1.5, fat: 0.2, carbs: 4.0, fiber: 4.2, tag: 'veggie' },
  { name: 'Thân chuối non bào', nameEn: 'Shredded banana trunk', calories: 12, protein: 0.5, fat: 0.1, carbs: 2.2, fiber: 3.5, tag: 'veggie' },
  { name: 'Rau muống chẻ', nameEn: 'Split water spinach strands', calories: 19, protein: 2.0, fat: 0.2, carbs: 2.3, fiber: 2.1, tag: 'veggie' },
  { name: 'Rau sắn muối chua', nameEn: 'Fermented cassava leaves', calories: 45, protein: 3.5, fat: 0.4, carbs: 6.8, fiber: 3.2, tag: 'veggie' },
  { name: 'Rau đắng', nameEn: 'Glinus oppositifolius / Bitter herb', calories: 22, protein: 2.1, fat: 0.2, carbs: 3.0, fiber: 1.9, tag: 'veggie' },
  { name: 'Rau càng cua', nameEn: 'Peperomia pellucida', calories: 24, protein: 1.3, fat: 0.2, carbs: 4.3, fiber: 1.1, tag: 'veggie' },
  { name: 'Rau dớn (Dương xỉ rừng)', nameEn: 'Wild vegetable fern', calories: 31, protein: 3.4, fat: 0.4, carbs: 3.5, fiber: 2.8, tag: 'veggie' },
  { name: 'Rau bò khai', nameEn: 'Erythropalum scandens', calories: 42, protein: 4.1, fat: 0.3, carbs: 5.8, fiber: 2.4, tag: 'veggie' },
  { name: 'Rau sắng (Rau ngót rừng)', nameEn: 'Wild sauropus / Melientha suavis leaves', calories: 48, protein: 6.5, fat: 0.4, carbs: 5.5, fiber: 2.8, tag: 'veggie' },
  { name: 'Rau lủi (Kim thất tai)', nameEn: 'Gynura procumbens', calories: 28, protein: 2.2, fat: 0.2, carbs: 4.4, fiber: 2.0, tag: 'veggie' },
  { name: 'Lá lốt tươi', nameEn: 'Piper lolot leaves', calories: 39, protein: 4.3, fat: 0.5, carbs: 4.4, fiber: 2.5, tag: 'veggie' },
  { name: 'Rau má ta', nameEn: 'Centella asiatica / Pennywort', calories: 20, protein: 3.2, fat: 0.1, carbs: 1.8, fiber: 2.0, tag: 'veggie' },
  { name: 'Rau mồng tơi tươi', nameEn: 'Malabar spinach', calories: 14, protein: 2.0, fat: 0.1, carbs: 1.4, fiber: 1.5, tag: 'veggie' },
  { name: 'Rau đay tươi', nameEn: 'Jute leaves', calories: 25, protein: 2.8, fat: 0.3, carbs: 3.0, fiber: 1.5, tag: 'veggie' },
  { name: 'Rau dền cơm', nameEn: 'Green amaranth', calories: 21, protein: 3.4, fat: 0.3, carbs: 1.1, fiber: 1.7, tag: 'veggie' },
  { name: 'Rau dền đỏ', nameEn: 'Red amaranth', calories: 41, protein: 3.3, fat: 0.3, carbs: 6.2, fiber: 1.7, tag: 'veggie' },
  { name: 'Rau cải cúc (Tần ô)', nameEn: 'Garland chrysanthemum', calories: 14, protein: 1.6, fat: 0.1, carbs: 1.9, fiber: 2.0, tag: 'veggie' },
  { name: 'Cải bẹ xanh (Cải cay)', nameEn: 'Kai choy / Mustard greens', calories: 16, protein: 1.7, fat: 0.2, carbs: 1.9, fiber: 1.7, tag: 'veggie' },
  { name: 'Cải ngọt', nameEn: 'Choy sum', calories: 18, protein: 1.6, fat: 0.2, carbs: 2.5, fiber: 1.6, tag: 'veggie' },
  { name: 'Cải ngóng', nameEn: 'Chinese broccoli flowering stem', calories: 22, protein: 1.9, fat: 0.2, carbs: 3.1, fiber: 2.0, tag: 'veggie' },
  { name: 'Cải bẹ dưa', nameEn: 'Mustard greens for pickling', calories: 15, protein: 1.5, fat: 0.2, carbs: 1.8, fiber: 1.6, tag: 'veggie' },
  { name: 'Cải cầu vồng', nameEn: 'Swiss chard', calories: 19, protein: 1.8, fat: 0.2, carbs: 3.7, fiber: 1.6, tag: 'veggie' },
  { name: 'Rau xà lách mỡ', nameEn: 'Butterhead lettuce', calories: 13, protein: 1.1, fat: 0.2, carbs: 2.2, fiber: 1.1, tag: 'veggie' },
  { name: 'Rau xà lách xoăn', nameEn: 'Looseleaf curly lettuce', calories: 15, protein: 1.4, fat: 0.2, carbs: 2.9, fiber: 1.3, tag: 'veggie' },
  { name: 'Xà lách Roman', nameEn: 'Romaine lettuce', calories: 17, protein: 1.2, fat: 0.3, carbs: 3.3, fiber: 2.1, tag: 'veggie' },
  { name: 'Rau diếp thơm', nameEn: 'Celtuce leaves / Taiwan lettuce', calories: 16, protein: 1.3, fat: 0.2, carbs: 2.3, fiber: 1.5, tag: 'veggie' },
  { name: 'Rau tiến vua (Khô)', nameEn: 'Dried mountain jellyfish vegetable', calories: 295, protein: 11.2, fat: 0.6, carbs: 61.2, fiber: 12.5, tag: 'veggie' },
  { name: 'Rau tai voi', nameEn: 'Baber leaf / Wild forest veggie', calories: 24, protein: 1.8, fat: 0.2, carbs: 3.8, fiber: 2.1, tag: 'veggie' },
  { name: 'Rau sam tươi', nameEn: 'Purslane', calories: 18, protein: 1.4, fat: 0.1, carbs: 3.0, fiber: 1.3, tag: 'veggie' },
  { name: 'Lá xương sông', nameEn: 'Blumea lanceolaria leaves', calories: 15, protein: 2.2, fat: 0.1, carbs: 1.5, fiber: 2.0, tag: 'veggie' },
  { name: 'Lá cách', nameEn: 'Premna serratifolia leaves', calories: 36, protein: 3.5, fat: 0.4, carbs: 4.6, fiber: 3.1, tag: 'veggie' },
  { name: 'Lá điên điển', nameEn: 'Sesbania sesban leaves', calories: 65, protein: 6.8, fat: 1.1, carbs: 7.2, fiber: 2.9, tag: 'veggie' },
  { name: 'Bông điên điển', nameEn: 'Sesbania sesban flower buds', calories: 28, protein: 2.5, fat: 0.3, carbs: 3.8, fiber: 2.1, tag: 'veggie' },
  { name: 'Bông so đũa', nameEn: 'Vegetable hummingbird blossoms', calories: 27, protein: 2.2, fat: 0.2, carbs: 4.1, fiber: 2.5, tag: 'veggie' },
  { name: 'Bông súng', nameEn: 'Water lily stems', calories: 11, protein: 0.5, fat: 0.1, carbs: 2.1, fiber: 1.4, tag: 'veggie' },
  { name: 'Bông hẹ', nameEn: 'Chive flowering chives', calories: 24, protein: 1.8, fat: 0.3, carbs: 3.5, fiber: 2.2, tag: 'veggie' },
  { name: 'Bông thiên lý', nameEn: 'Telosma cordata blossoms', calories: 23, protein: 2.9, fat: 0.1, carbs: 2.8, fiber: 3.0, tag: 'veggie' },
  { name: 'Kèo nèo (Cù nèo)', nameEn: 'Yellow velvetleaf stems', calories: 14, protein: 0.8, fat: 0.1, carbs: 2.5, fiber: 1.6, tag: 'veggie' },
  { name: 'Rau mác', nameEn: 'Sagittaria sagittifolia leaves', calories: 18, protein: 1.4, fat: 0.1, carbs: 2.9, fiber: 1.7, tag: 'veggie' },
  { name: 'Rau trai (Thài lài trắng)', nameEn: 'Common dayflower leaves', calories: 16, protein: 1.2, fat: 0.1, carbs: 2.6, fiber: 1.8, tag: 'veggie' },
  { name: 'Rau dừa nước', nameEn: 'Water primrose', calories: 15, protein: 1.5, fat: 0.1, carbs: 2.1, fiber: 1.6, tag: 'veggie' },
  { name: 'Rau má hương', nameEn: 'Hydrocotyle sibthorpioides', calories: 19, protein: 1.8, fat: 0.1, carbs: 2.8, fiber: 1.5, tag: 'veggie' },
  { name: 'Rau diếp cá tươi', nameEn: 'Fish mint / Heartleaf', calories: 22, protein: 2.9, fat: 0.1, carbs: 2.7, fiber: 1.8, tag: 'veggie' },
  { name: 'Cà phê đen nóng (ko đường)', nameEn: 'Vietnamese Hot Black Coffee (No Sugar)', calories: 5, protein: 0.4, fat: 0.1, carbs: 0.8, tag: 'coffee' },
  { name: 'Cà phê sữa đá Sài Gòn', nameEn: 'Vietnamese Iced Coffee with Condensed Milk', calories: 185, protein: 3.5, fat: 5.2, carbs: 31.2, tag: 'coffee' },
  { name: 'Bạc xỉu đá', nameEn: 'White Coffee with Iced Condensed Milk', calories: 245, protein: 4.8, fat: 6.5, carbs: 41.8, tag: 'coffee' },
  { name: 'Cà phê trứng nóng', nameEn: 'Vietnamese Egg Coffee', calories: 210, protein: 7.2, fat: 9.8, carbs: 23.5, tag: 'coffee' },
  { name: 'Cà phê muối đá', nameEn: 'Vietnamese Salted Cream Iced Coffee', calories: 195, protein: 2.1, fat: 12.4, carbs: 18.8, tag: 'coffee' },
  { name: 'Cà phê cốt dừa đá xay', nameEn: 'Coconut Frozen Coffee', calories: 320, protein: 3.2, fat: 18.5, carbs: 35.4, tag: 'coffee' },
  { name: 'Espresso (Double shot)', nameEn: 'Espresso (Double Shot)', calories: 5, protein: 0.5, fat: 0.1, carbs: 0.6, tag: 'coffee' },
  { name: 'Cà phê Americano đá', nameEn: 'Iced Americano', calories: 5, protein: 0.4, fat: 0.1, carbs: 0.8, tag: 'coffee' },
  { name: 'Cà phê Latte nóng (Sữa tươi nguyên kem)', nameEn: 'Hot Latte (Whole Milk)', calories: 140, protein: 8, fat: 7.4, carbs: 10.5, tag: 'coffee' },
  { name: 'Cà phê Latte đá (Sữa tươi ít béo)', nameEn: 'Iced Latte (Low-fat Milk)', calories: 90, protein: 7.5, fat: 2.2, carbs: 10.1, tag: 'coffee' },
  { name: 'Cà phê Cappuccino nóng', nameEn: 'Hot Cappuccino', calories: 120, protein: 6.8, fat: 6.2, carbs: 9.2, tag: 'coffee' },
  { name: 'Cà phê Cold Brew (Ủ lạnh nguyên bản)', nameEn: 'Cold Brew Coffee (Plain)', calories: 5, protein: 0.3, fat: 0, carbs: 0.7, tag: 'coffee' },
  { name: 'Cold Brew Cam Sả', nameEn: 'Cold Brew with Orange and Lemongrass', calories: 65, protein: 0.6, fat: 0.1, carbs: 15.2, tag: 'coffee' },
  { name: 'Cà phê Caramel Macchiato đá', nameEn: 'Iced Caramel Macchiato', calories: 230, protein: 6.2, fat: 6.8, carbs: 35.5, tag: 'coffee' },
  { name: 'Cà phê Mocha đá', nameEn: 'Iced Caffè Mocha', calories: 260, protein: 7.1, fat: 8.2, carbs: 39.4, tag: 'coffee' },
  { name: 'Cà phê Flat White', nameEn: 'Flat White', calories: 120, protein: 7, fat: 6.2, carbs: 9, tag: 'coffee' },
  { name: 'Cà phê đen đá có đường (1 thìa)', nameEn: 'Vietnamese Black Iced Coffee with Sugar', calories: 55, protein: 0.4, fat: 0.1, carbs: 13.2, tag: 'coffee' },
  { name: 'Espresso Macchiato', nameEn: 'Espresso Macchiato', calories: 15, protein: 0.8, fat: 0.5, carbs: 1.2, tag: 'coffee' },
  { name: 'Affogato (Espresso kèm 1 viên kem vani)', nameEn: 'Affogato (Espresso with Vanilla Ice Cream)', calories: 145, protein: 2.5, fat: 7.8, carbs: 16.2, tag: 'coffee' },
  { name: 'Cơm trắng', nameEn: 'White Rice', calories: 130, protein: 2.7, fat: 0.3, carbs: 28.2, tag: 'starch' },
  { name: 'Cơm lứt', nameEn: 'Brown Rice', calories: 111, protein: 2.6, fat: 0.9, carbs: 23, tag: 'starch' },
  { name: 'Xôi trắng', nameEn: 'Sticky Rice', calories: 344, protein: 6.5, fat: 1.2, carbs: 74.9, tag: 'starch' },
  { name: 'Xôi đậu', nameEn: 'Sticky Rice with Beans', calories: 310, protein: 8.2, fat: 2.1, carbs: 62.4, tag: 'starch' },
  { name: 'Yến mạch', nameEn: 'Oats', calories: 389, protein: 16.9, fat: 6.9, carbs: 66.3, tag: 'starch' },
  { name: 'Bánh mỳ trắng', nameEn: 'White Bread', calories: 265, protein: 9, fat: 3.2, carbs: 49, tag: 'starch' },
  { name: 'Bánh mỳ nguyên cám', nameEn: 'Whole Wheat Bread', calories: 247, protein: 13, fat: 3.4, carbs: 41.3, tag: 'starch' },
  { name: 'Bánh mỳ đen', nameEn: 'Rye Bread', calories: 259, protein: 8.5, fat: 3.3, carbs: 48.3, tag: 'starch' },
  { name: 'Mỳ Spaghetti (sống)', nameEn: 'Spaghetti Pasta (Raw)', calories: 371, protein: 13, fat: 1.5, carbs: 75, tag: 'starch' },
  { name: 'Khoai tây (sống)', nameEn: 'Potato (Raw)', calories: 77, protein: 2, fat: 0.1, carbs: 17, fiber: 2.2, tag: 'veggie' },
  { name: 'Khoai môn (chín)', nameEn: 'Taro (Cooked)', calories: 142, protein: 0.7, fat: 0.1, carbs: 34.6, fiber: 5.1, tag: 'veggie' },
  { name: 'Khoai lang ruột cam (thường) chín', nameEn: 'Orange Sweet Potato (Cooked)', calories: 86, protein: 1.6, fat: 0.1, carbs: 20.1, fiber: 3, tag: 'veggie' },
  { name: 'Khoai lang ruột cam (Nhật) chín', nameEn: 'Japanese Sweet Potato (Cooked)', calories: 115, protein: 1.5, fat: 0.2, carbs: 26.5, fiber: 3.3, tag: 'veggie' },
  { name: 'Khoai sọ (chín)', nameEn: 'Taro Root (Cooked)', calories: 116, protein: 1.5, fat: 0.2, carbs: 26.4, fiber: 3.9, tag: 'veggie' },
  { name: 'Bánh mì kẹp thịt nướng và rau thơm, ko sốt mayonaise (bán lề đường)', nameEn: 'Street Banh Mi with Grilled Pork', calories: 395, protein: 15.5, fat: 11.2, carbs: 48.5, tag: 'meal' },
  { name: 'Bánh mì pate trứng, và rau thơm, ko sốt mayonaise (bán lề đường)', nameEn: 'Street Banh Mi with Pate and Egg', calories: 410, protein: 14.2, fat: 16.8, carbs: 46.2, tag: 'meal' },
  { name: 'Phở bò tái', nameEn: 'Beef Pho (Rare)', calories: 430, protein: 22.4, fat: 8.5, carbs: 54.3, tag: 'meal' },
  { name: 'Phở bò chín', nameEn: 'Beef Pho (Well-done)', calories: 445, protein: 24.1, fat: 9.2, carbs: 54.3, tag: 'meal' },
  { name: 'Phở bò nạm', nameEn: 'Beef Pho (Flank)', calories: 480, protein: 23.5, fat: 13.8, carbs: 54.3, tag: 'meal' },
  { name: 'Phở bò gầu', nameEn: 'Beef Pho (Brisket)', calories: 520, protein: 21.2, fat: 19.5, carbs: 54.3, tag: 'meal' },
  { name: 'Phở bò xào', nameEn: 'Stir-fried Beef Pho', calories: 650, protein: 26.8, fat: 24.5, carbs: 68.2, tag: 'meal' },
  { name: 'Phở gà (ko da)', nameEn: 'Chicken Pho (Skinless)', calories: 385, protein: 25.2, fat: 5.4, carbs: 55.1, tag: 'meal' },
  { name: 'Phở gà (cả da)', nameEn: 'Chicken Pho (With Skin)', calories: 440, protein: 23.8, fat: 12.1, carbs: 55.1, tag: 'meal' },
  { name: 'Phở cuốn', nameEn: 'Pho Rolls', calories: 380, protein: 16.5, fat: 9.8, carbs: 45.2, tag: 'meal' },
  { name: 'Gỏi cuốn tôm thịt', nameEn: 'Fresh Spring Rolls with Shrimp and Pork', calories: 320, protein: 19.4, fat: 7.2, carbs: 36.5, tag: 'meal' },
  { name: 'Gỏi cuốn thịt', nameEn: 'Fresh Spring Rolls with Pork', calories: 345, protein: 15.2, fat: 11.5, carbs: 36.5, tag: 'meal' },
  { name: 'Bún ốc', nameEn: 'Snail Rice Noodle', calories: 390, protein: 16.2, fat: 6.5, carbs: 58.4, tag: 'meal' },
  { name: 'Bún bò', nameEn: 'Beef Rice Noodle', calories: 470, protein: 22.1, fat: 12.4, carbs: 56.5, tag: 'meal' },
  { name: 'Bún vịt', nameEn: 'Duck Rice Noodle', calories: 515, protein: 21.8, fat: 18.2, carbs: 55.3, tag: 'meal' },
  { name: 'Bún ngan', nameEn: 'Goose Rice Noodle', calories: 495, protein: 23.2, fat: 15.5, carbs: 55.3, tag: 'meal' },
  { name: 'Bún mọc', nameEn: 'Pork Ball Rice Noodle', calories: 425, protein: 19.5, fat: 10.2, carbs: 54.8, tag: 'meal' },
  { name: 'Bánh đa cá cay', nameEn: 'Spicy Fish Flat Rice Noodle', calories: 460, protein: 21.4, fat: 11.8, carbs: 59.5, tag: 'meal' },
  { name: 'Bún cá cay', nameEn: 'Spicy Fish Rice Noodle', calories: 450, protein: 20.8, fat: 11.2, carbs: 58.7, tag: 'meal' },
  { name: 'Vịt quay', nameEn: 'Roasted Duck', calories: 337, protein: 19, fat: 28, carbs: 0, tag: 'protein' },
  { name: 'Gà quay', nameEn: 'Roasted Chicken', calories: 240, protein: 23, fat: 15, carbs: 1, tag: 'protein' },
  { name: 'Thịt nướng', nameEn: 'Grilled Pork', calories: 253, protein: 22.1, fat: 17.4, carbs: 1.5, tag: 'protein' },
  { name: 'Xôi xéo ruốc', nameEn: 'Sticky Rice with Mung Bean and Pork Floss', calories: 465, protein: 11.2, fat: 12.8, carbs: 75.4, tag: 'meal' },
  { name: 'Xôi thập cẩm', nameEn: 'Combination Sticky Rice', calories: 530, protein: 16.5, fat: 18.2, carbs: 73.1, tag: 'meal' },
  { name: 'Thịt xiên nướng (xiên nhỏ)', nameEn: 'Small Grilled Pork Skewer', calories: 125, protein: 7.8, fat: 8.5, carbs: 3.2, tag: 'meal' },
  { name: 'Bánh tráng trộn', nameEn: 'Rice Paper Salad', calories: 310, protein: 6.4, fat: 14.2, carbs: 38.5, tag: 'junk' },
  { name: 'Nem nướng', nameEn: 'Grilled Pork Sausage', calories: 245, protein: 16.8, fat: 16.2, carbs: 7.5, tag: 'meal' },
  { name: 'Khoai tây chiên', nameEn: 'French Fries', calories: 312, protein: 3.4, fat: 15, carbs: 41, tag: 'junk' },
  { name: 'Nem chua rán', nameEn: 'Fried Fermented Pork Roll', calories: 135, protein: 5.2, fat: 8.4, carbs: 9.8, tag: 'junk' },
  { name: 'Bánh giò', nameEn: 'Pyramid Rice Dumpling', calories: 360, protein: 9.5, fat: 16.2, carbs: 43.8, tag: 'meal' },
  { name: 'Cơm gà nướng', nameEn: 'Grilled Chicken Rice', calories: 580, protein: 29.5, fat: 14.8, carbs: 75.2, tag: 'meal' },
  { name: 'Mỳ xào bò', nameEn: 'Stir-fried Noodles with Beef', calories: 590, protein: 24.5, fat: 21.2, carbs: 67.4, tag: 'meal' },
  { name: 'Bánh cuốn', nameEn: 'Steamed Rice Rolls', calories: 345, protein: 8.9, fat: 10.5, carbs: 53.2, tag: 'meal' },
  { name: 'Bánh chuối', nameEn: 'Fried Banana Cake', calories: 225, protein: 2.1, fat: 8.3, carbs: 36.4, tag: 'junk' },
  { name: 'Bánh khoai', nameEn: 'Fried Sweet Potato Cake', calories: 240, protein: 2.4, fat: 9.1, carbs: 37.8, tag: 'junk' },
  { name: 'Bánh gối', nameEn: 'Pillow Cake', calories: 295, protein: 8.2, fat: 15.4, carbs: 31.2, tag: 'junk' },
  { name: 'Hoa quả dầm sữa chua', nameEn: 'Fruit Salad with Yogurt', calories: 180, protein: 4.2, fat: 2.5, carbs: 34.5, fiber: 1.8, tag: 'fruit' },
  { name: 'Whey Protein (Chung)', nameEn: 'Whey Protein (General)', calories: 120, protein: 25, fat: 1, carbs: 2, tag: 'protein' },
  { name: 'Đậu phụ', nameEn: 'Soybean curt cake pressed, raw', calories: 95, protein: 10.91, fat: 5.41, carbs: 0.71, tag: 'protein' },
  { name: 'Mực ống', nameEn: 'Squid', calories: 92, protein: 15.6, fat: 1.4, carbs: 3.1, tag: 'protein' },
  { name: 'Ốc', nameEn: 'Snails', calories: 84, protein: 14.2, fat: 0.7, carbs: 3.9, tag: 'protein' },
  { name: 'Trứng vịt lộn', nameEn: 'Duck egg, embryonated', calories: 182, protein: 13.61, fat: 12.41, carbs: 4.01, tag: 'protein' },
  { name: 'Thịt ức bò(nạc)', nameEn: 'Lean Beef Brisket', calories: 155, protein: 21.5, fat: 7.2, carbs: 0, tag: 'protein' },
  { name: 'Thịt ức bò(nạc+mỡ)', nameEn: 'Beef Brisket (Fat and Lean)', calories: 245, protein: 18.2, fat: 18.8, carbs: 0, tag: 'protein' },
  { name: 'Tai lợn', nameEn: 'Hog ears', calories: 126, protein: 21.01, fat: 4.11, carbs: 1.31, tag: 'protein' },
  { name: 'Cá hồi file (phần giữa)', nameEn: 'Salmon Fillet (Center Cut)', calories: 208, protein: 20, fat: 13, carbs: 0, tag: 'protein' },
  { name: 'Cá hồi phile (phần đuôi)', nameEn: 'Salmon Fillet (Tail Cut)', calories: 185, protein: 21.2, fat: 10.5, carbs: 0, tag: 'protein' },
  { name: 'Cá chép giòn', nameEn: 'Crunchy Carp Fish', calories: 120, protein: 18.5, fat: 4.8, carbs: 0, tag: 'protein' },
  { name: 'Cá chép thường', nameEn: 'Common Carp Fish', calories: 96, protein: 16, fat: 3.6, carbs: 0, tag: 'protein' },
  { name: 'Cá trắm', nameEn: 'Grass Carp Fish', calories: 91, protein: 17, fat: 2.6, carbs: 0, tag: 'protein' },
  { name: 'Cá trôi', nameEn: 'Major carp, mud carp; cirrhina molitorella', calories: 127, protein: 18.81, fat: 5.71, carbs: 0.01, tag: 'protein' },
  { name: 'Cá quả', nameEn: 'Fish, snake head', calories: 97, protein: 18.21, fat: 2.71, carbs: 0.01, tag: 'protein' },
  { name: 'Cá rô phi', nameEn: 'Tilapia, African carp', calories: 100, protein: 19.71, fat: 2.31, carbs: 0.01, tag: 'protein' },
  { name: 'Cá nục 1 nắng', nameEn: 'Semi-dried Mackerel', calories: 165, protein: 20.2, fat: 9.1, carbs: 0, tag: 'protein' },
  { name: 'Cá ngừ 1 nắng', nameEn: 'Semi-dried Tuna', calories: 154, protein: 24.8, fat: 5.5, carbs: 0, tag: 'protein' },
  { name: 'Cá mè', nameEn: 'Bighead Carp Fish', calories: 114, protein: 15.4, fat: 5.8, carbs: 0, tag: 'protein' },
  { name: 'Tôm', nameEn: 'Shrimp', calories: 99, protein: 24, fat: 0.3, carbs: 0.2, tag: 'protein' },
  { name: 'Thịt vịt (chung)', nameEn: 'Duck meat, average', calories: 267, protein: 17.81, fat: 21.81, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt ngan (chung)', nameEn: 'Goose Meat (General)', calories: 254, protein: 16.2, fat: 20.5, carbs: 0, tag: 'protein' },
  { name: 'Cánh gà thịt và da', nameEn: 'Chicken Wing with Skin', calories: 203, protein: 26.9, fat: 9.9, carbs: 0, tag: 'protein' },
  { name: 'Chân gà thịt và da', nameEn: 'Chicken Feet with Skin', calories: 215, protein: 19.4, fat: 14.6, carbs: 0.2, tag: 'protein' },
  { name: 'Cổ gà thịt và da', nameEn: 'Chicken Neck with Skin', calories: 234, protein: 14.5, fat: 19.2, carbs: 0, tag: 'protein' },
  { name: 'Da gà', nameEn: 'Chicken Skin', calories: 440, protein: 11.2, fat: 44.1, carbs: 0, tag: 'protein' },
  { name: 'Thăn lợn nạc', nameEn: 'Lean Pork Tenderloin', calories: 143, protein: 26, fat: 3.5, carbs: 0, tag: 'protein' },
  { name: 'Thăn lợn nạc + mỡ', nameEn: 'Pork Loin with Fat', calories: 242, protein: 22.1, fat: 16.5, carbs: 0, tag: 'protein' },
  { name: 'Thịt vai nạc', nameEn: 'Lean Pork Shoulder', calories: 148, protein: 23.4, fat: 5.8, carbs: 0, tag: 'protein' },
  { name: 'Thịt vai nạc + mỡ', nameEn: 'Pork Shoulder with Fat', calories: 265, protein: 18.5, fat: 21.2, carbs: 0, tag: 'protein' },
  { name: 'Thịt chân giò nạc + mỡ', nameEn: 'Pork Shank with Fat', calories: 231, protein: 19.2, fat: 16.8, carbs: 0, tag: 'protein' },
  { name: 'Thịt sườn nạc + mỡ', nameEn: 'Pork Ribs with Fat', calories: 275, protein: 17.4, fat: 22.5, carbs: 0, tag: 'protein' },
  { name: 'Lạc (đã bỏ vỏ)', nameEn: 'Peanuts (Shelled)', calories: 567, protein: 25.8, fat: 49.2, carbs: 16.1, tag: 'protein' },
  { name: 'Đậu phụ rán', nameEn: 'Fried Tofu', calories: 271, protein: 17.2, fat: 20.1, carbs: 2.9, tag: 'protein' },
  { name: 'Cùi dừa già', nameEn: 'Coconut meat, mature, raw', calories: 368, protein: 4.81, fat: 36.01, carbs: 6.21, tag: 'fat' },
  { name: 'Cùi dừa non', nameEn: 'Coconut meat, immature, raw', calories: 40, protein: 3.51, fat: 1.71, carbs: 2.61, tag: 'fat' },
  { name: 'Hạt macca (đã bỏ vỏ)', nameEn: 'Macadamia Nuts (Shelled)', calories: 718, protein: 7.9, fat: 75.8, carbs: 13.8, tag: 'fat' },
  { name: 'Hạt hướng dương (đã bỏ vỏ)', nameEn: 'Sunflower Seeds (Shelled)', calories: 584, protein: 20.8, fat: 51.5, carbs: 20, tag: 'fat' },
  { name: 'Hạt điều (đã bỏ vỏ)', nameEn: 'Cashew Nuts (Shelled)', calories: 553, protein: 18.2, fat: 43.8, carbs: 30.2, tag: 'fat' },
  { name: 'Phô mai (Cheddar)', nameEn: 'Cheddar Cheese', calories: 403, protein: 24.9, fat: 33.1, carbs: 1.3, tag: 'dairy' },
  { name: 'Hạt dẻ (đã bỏ vỏ)', nameEn: 'Chestnuts (Shelled)', calories: 131, protein: 2, fat: 1.4, carbs: 28, tag: 'starch' },
  { name: 'Hạnh nhân (đã bỏ vỏ)', nameEn: 'Almonds (Shelled)', calories: 579, protein: 21.2, fat: 49.9, carbs: 21.6, tag: 'fat' },
  { name: 'Hột é', nameEn: 'Basil Seeds', calories: 22, protein: 2, fat: 0.5, carbs: 4, tag: 'veggie' },
  { name: 'Bơ President', nameEn: 'President Butter', calories: 743, protein: 0.7, fat: 82, carbs: 0.7, tag: 'fat' },
  { name: 'Bơ đậu phộng', nameEn: 'Peanut Butter', calories: 588, protein: 25, fat: 50, carbs: 20, tag: 'fat' },
  { name: 'Phô mai Mozzarella', nameEn: 'Mozzarella Cheese', calories: 280, protein: 22, fat: 17, carbs: 3.1, tag: 'dairy' },
  { name: 'Phô mai con bò cười', nameEn: 'The Laughing Cow Cheese', calories: 250, protein: 11, fat: 22, carbs: 5, tag: 'dairy' },
  { name: 'Dầu ăn (Chung)', nameEn: 'Cooking Oil (General)', calories: 884, protein: 0, fat: 100, carbs: 0, tag: 'fat' },
  { name: 'Su su', nameEn: 'Chayote', calories: 19, protein: 0.8, fat: 0.1, carbs: 4.5, fiber: 1.7, tag: 'veggie' },
  { name: 'Su hào', nameEn: 'Kohlrabi', calories: 37, protein: 2.81, fat: 0.13, carbs: 6.21, fiber: 3.6, tag: 'veggie' },
  { name: 'Súp lơ xanh', nameEn: 'Broccoli', calories: 34, protein: 2.8, fat: 0.4, carbs: 6.6, fiber: 2.6, tag: 'veggie' },
  { name: 'Súp lơ trắng', nameEn: 'Cauliflower, white', calories: 30, protein: 2.51, fat: 0.13, carbs: 4.81, fiber: 2, tag: 'veggie' },
  { name: 'Dưa chuột', nameEn: 'Cucumber', calories: 16, protein: 0.81, fat: 0.13, carbs: 2.91, fiber: 0.5, tag: 'veggie' },
  { name: 'Cần tây', nameEn: 'Celery, Chinese', calories: 48, protein: 3.71, fat: 0.23, carbs: 7.91, fiber: 1.6, tag: 'veggie' },
  { name: 'Măng tây', nameEn: 'Asparagus, white', calories: 14, protein: 2.21, fat: 0.13, carbs: 1.11, fiber: 2.1, tag: 'veggie' },
  { name: 'Rau muống', nameEn: 'Swamp cabbage, water spinach, water convol', calories: 25, protein: 3.21, fat: 0.43, carbs: 2.11, fiber: 2.1, tag: 'veggie' },
  { name: 'Cà chua', nameEn: 'Tomato', calories: 20, protein: 0.61, fat: 0.23, carbs: 4.01, fiber: 1.2, tag: 'veggie' },
  { name: 'Cà rốt', nameEn: 'Carrot', calories: 41, protein: 0.9, fat: 0.2, carbs: 9.6, fiber: 2.8, tag: 'veggie' },
  { name: 'Bí xanh (Bí non)', nameEn: 'Winter Melon', calories: 12, protein: 0.4, fat: 0.1, carbs: 2.4, fiber: 1, tag: 'veggie' },
  { name: 'Ngô ngọt', nameEn: 'Sweet Corn', calories: 86, protein: 3.2, fat: 1.2, carbs: 19, fiber: 2.7, tag: 'veggie' },
  { name: 'Ngô bao tử', nameEn: 'Corn, small variety immature, baby corn', calories: 40, protein: 2.21, fat: 0.21, carbs: 7.41, fiber: 1.6, tag: 'veggie' },
  { name: 'Cà tím', nameEn: 'Aubergine', calories: 22, protein: 1.01, fat: 0, carbs: 4.51, fiber: 3, tag: 'veggie' },
  { name: 'Xà lách', nameEn: 'Lettuce, garden asparagus', calories: 17, protein: 1.51, fat: 0.45, carbs: 1.81, fiber: 1.3, tag: 'veggie' },
  { name: 'Nấm hải sản', nameEn: 'Shimeji Mushroom', calories: 33, protein: 2.5, fat: 0.4, carbs: 6.2, tag: 'veggie' },
  { name: 'Nấm đùi gà', nameEn: 'King Oyster Mushroom', calories: 35, protein: 2.9, fat: 0.3, carbs: 6.5, tag: 'veggie' },
  { name: 'Nấm mỡ trắng', nameEn: 'White Button Mushroom', calories: 22, protein: 3.1, fat: 0.3, carbs: 3.3, tag: 'veggie' },
  { name: 'Nấm mỡ nâu', nameEn: 'Cremini Mushroom', calories: 22, protein: 2.5, fat: 0.1, carbs: 4.3, tag: 'veggie' },
  { name: 'Củ đậu', nameEn: 'Pachyrrhizus', calories: 28, protein: 1.01, fat: 0, carbs: 6.01, fiber: 4.9, tag: 'veggie' },
  { name: 'Cải xoăn', nameEn: 'Kale', calories: 49, protein: 4.3, fat: 0.9, carbs: 8.8, fiber: 3.6, tag: 'veggie' },
  { name: 'Bí đỏ', nameEn: 'Pumpkin', calories: 26, protein: 1, fat: 0.1, carbs: 6.5, fiber: 0.5, tag: 'veggie' },
  { name: 'Bầu', nameEn: 'Calabash, Bottle gourd', calories: 14, protein: 0.61, fat: 0.023, carbs: 2.91, fiber: 0.6, tag: 'veggie' },
  { name: 'Bí đao', nameEn: 'Wax Gourd', calories: 13, protein: 0.4, fat: 0.1, carbs: 2.8, fiber: 1, tag: 'veggie' },
  { name: 'Mướp', nameEn: 'Gourd, sponge gourd', calories: 17, protein: 0.91, fat: 0.23, carbs: 2.81, fiber: 0.5, tag: 'veggie' },
  { name: 'Cải bắp', nameEn: 'Cabbage, common', calories: 29, protein: 1.81, fat: 0.13, carbs: 5.31, fiber: 2.5, tag: 'veggie' },
  { name: 'Rau cải (Chung)', nameEn: 'Mustard Greens', calories: 27, protein: 2.7, fat: 0.4, carbs: 4.7, fiber: 2, tag: 'veggie' },
  { name: 'Cải thảo', nameEn: 'Napa Cabbage', calories: 16, protein: 1.2, fat: 0.2, carbs: 3.2, fiber: 1.2, tag: 'veggie' },
  { name: 'Giá đỗ', nameEn: 'Bean Sprouts', calories: 30, protein: 4, fat: 0.2, carbs: 4.1, fiber: 1.9, tag: 'veggie' },
  { name: 'Ớt chuông đỏ', nameEn: 'Red bell pepper', calories: 31, protein: 1, fat: 0.3, carbs: 6, fiber: 2.1, tag: 'veggie' },
  { name: 'Ớt chuông xanh', nameEn: 'Green bell pepper', calories: 20, protein: 0.9, fat: 0.2, carbs: 4.6, fiber: 1.7, tag: 'veggie' },
  { name: 'Ớt chuông vàng', nameEn: 'Yellow bell pepper', calories: 27, protein: 1, fat: 0.2, carbs: 6.3, fiber: 0.9, tag: 'veggie' },
  { name: 'Mướp đắng (Khổ qua)', nameEn: 'Bitter melon / Bitter gourd', calories: 17, protein: 1, fat: 0.2, carbs: 3.7, fiber: 2.8, tag: 'veggie' },
  { name: 'Khổ qua rừng', nameEn: 'Wild bitter melon', calories: 19, protein: 1.1, fat: 0.2, carbs: 4, fiber: 3.1, tag: 'veggie' },
  { name: 'Đậu bắp', nameEn: 'Okra', calories: 33, protein: 1.9, fat: 0.2, carbs: 7.5, fiber: 3.2, tag: 'veggie' },
  { name: 'Đậu cô ve tươi (quả)', nameEn: 'Green beans, fresh pods', calories: 31, protein: 1.8, fat: 0.2, carbs: 7, fiber: 3.4, tag: 'veggie' },
  { name: 'Đậu đũa tươi (quả)', nameEn: 'Yardlong beans, fresh pods', calories: 47, protein: 2.8, fat: 0.4, carbs: 8, fiber: 3, tag: 'veggie' },
  { name: 'Đậu Hà Lan tươi (hạt)', nameEn: 'Green peas, fresh', calories: 81, protein: 5.4, fat: 0.4, carbs: 14.5, fiber: 5.7, tag: 'veggie' },
  { name: 'Đậu Hà Lan non (quả dẹt)', nameEn: 'Snow peas / Sugar snap peas', calories: 42, protein: 2.8, fat: 0.2, carbs: 7.5, fiber: 2.6, tag: 'veggie' },
  { name: 'Đậu rồng (quả)', nameEn: 'Winged bean pods', calories: 49, protein: 6.9, fat: 0.9, carbs: 4.3, fiber: 2.6, tag: 'veggie' },
  { name: 'Hành tây', nameEn: 'Onion', calories: 40, protein: 1.1, fat: 0.1, carbs: 9.3, fiber: 1.7, tag: 'veggie' },
  { name: 'Hành tím', nameEn: 'Shallot', calories: 72, protein: 2.5, fat: 0.1, carbs: 16.8, fiber: 3.2, tag: 'veggie' },
  { name: 'Hành lá', nameEn: 'Scallion / Green onion', calories: 32, protein: 1.8, fat: 0.2, carbs: 7.3, fiber: 2.6, tag: 'veggie' },
  { name: 'Hẹ lá', nameEn: 'Garlic chives', calories: 30, protein: 3.3, fat: 0.7, carbs: 4.4, fiber: 2.5, tag: 'veggie' },
  { name: 'Tỏi', nameEn: 'Garlic', calories: 149, protein: 6.4, fat: 0.5, carbs: 33, fiber: 2.1, tag: 'veggie' },
  { name: 'Tỏi tây (Boa rô)', nameEn: 'Leek', calories: 61, protein: 1.5, fat: 0.3, carbs: 14.2, fiber: 1.8, tag: 'veggie' },
  { name: 'Sả', nameEn: 'Lemongrass', calories: 99, protein: 1.8, fat: 0.5, carbs: 25.3, fiber: 1.5, tag: 'veggie' },
  { name: 'Ớt tươi (ớt cay)', nameEn: 'Fresh chili pepper', calories: 40, protein: 1.9, fat: 0.4, carbs: 8.8, fiber: 1.5, tag: 'veggie' },
  { name: 'Củ cải trắng', nameEn: 'Daikon / White radish', calories: 18, protein: 0.6, fat: 0.1, carbs: 4.1, fiber: 1.6, tag: 'veggie' },
  { name: 'Củ cải đỏ', nameEn: 'Red radish', calories: 16, protein: 0.7, fat: 0.1, carbs: 3.4, fiber: 1.6, tag: 'veggie' },
  { name: 'Củ dền', nameEn: 'Beetroot', calories: 43, protein: 1.6, fat: 0.2, carbs: 9.6, fiber: 2.8, tag: 'veggie' },
  { name: 'Cải bó xôi (Rau chân vịt)', nameEn: 'Spinach', calories: 23, protein: 2.9, fat: 0.4, carbs: 3.6, fiber: 2.2, tag: 'veggie' },
  { name: 'Bắp cải tím', nameEn: 'Red cabbage', calories: 31, protein: 1.4, fat: 0.2, carbs: 7.4, fiber: 2.1, tag: 'veggie' },
  { name: 'Atiso', nameEn: 'Artichoke', calories: 47, protein: 3.3, fat: 0.2, carbs: 10.5, fiber: 5.4, tag: 'veggie' },
  { name: 'Dọc mùng (Bạc hà)', nameEn: 'Taro stem', calories: 14, protein: 0.3, fat: 0.1, carbs: 3.1, fiber: 1.2, tag: 'veggie' },
  { name: 'Ngó sen', nameEn: 'Lotus root', calories: 74, protein: 2.6, fat: 0.1, carbs: 17.2, fiber: 4.9, tag: 'veggie' },
  { name: 'Măng tươi', nameEn: 'Bamboo shoots, fresh', calories: 27, protein: 2.6, fat: 0.3, carbs: 5.2, fiber: 2.2, tag: 'veggie' },
  { name: 'Măng chua', nameEn: 'Pickled sour bamboo shoots', calories: 20, protein: 1.8, fat: 0.2, carbs: 3.5, fiber: 2, tag: 'veggie' },
  { name: 'Măng khô', nameEn: 'Dried bamboo shoots', calories: 196, protein: 13, fat: 0.8, carbs: 36, fiber: 13, tag: 'veggie' },
  { name: 'Cải Brussels (Bắp cải tí hon)', nameEn: 'Brussels sprouts', calories: 43, protein: 3.4, fat: 0.3, carbs: 9, fiber: 3.8, tag: 'veggie' },
  { name: 'Rau cần ta', nameEn: 'Water dropwort / Vietnamese celery', calories: 16, protein: 1.5, fat: 0.2, carbs: 2.3, fiber: 1.8, tag: 'veggie' },
  { name: 'Rau nhút', nameEn: 'Water mimosa', calories: 28, protein: 3.2, fat: 0.3, carbs: 3.4, fiber: 2.5, tag: 'veggie' },
  { name: 'Cà pháo', nameEn: 'Thai round eggplant', calories: 24, protein: 1.2, fat: 0.2, carbs: 5, fiber: 3, tag: 'veggie' },
  { name: 'Bí ngòi (Bí Ý)', nameEn: 'Zucchini', calories: 17, protein: 1.2, fat: 0.3, carbs: 3.1, fiber: 1, tag: 'veggie' },
  { name: 'Cà chua bi', nameEn: 'Cherry tomato', calories: 18, protein: 0.9, fat: 0.2, carbs: 3.9, fiber: 1.2, tag: 'veggie' },
  { name: 'Măng tây xanh', nameEn: 'Green asparagus', calories: 20, protein: 2.2, fat: 0.1, carbs: 3.9, fiber: 2.1, tag: 'veggie' },
  { name: 'Khoai mỡ (Khoai tím)', nameEn: 'Purple yam', calories: 118, protein: 1.5, fat: 0.2, carbs: 27.9, fiber: 4.1, tag: 'veggie' },
  { name: 'Củ niễng', nameEn: 'Manchurian wild rice stem', calories: 26, protein: 1.2, fat: 0.2, carbs: 5.3, fiber: 2.8, tag: 'veggie' },
  { name: 'Lá giang', nameEn: 'Sour creeper leaves', calories: 23, protein: 2.3, fat: 0.2, carbs: 3.2, fiber: 2, tag: 'veggie' },
  { name: 'Bồ công anh', nameEn: 'Dandelion greens', calories: 45, protein: 2.7, fat: 0.7, carbs: 9.2, fiber: 3.5, tag: 'veggie' },
  { name: 'Rau arugula (Cải lông)', nameEn: 'Arugula / Rocket', calories: 25, protein: 2.6, fat: 0.7, carbs: 3.7, fiber: 1.6, tag: 'veggie' },
  { name: 'Nấm kim châm', nameEn: 'Enoki mushroom', calories: 37, protein: 2.7, fat: 0.3, carbs: 7.8, fiber: 2.7, tag: 'veggie' },
  { name: 'Nấm bào ngư', nameEn: 'Oyster mushroom', calories: 33, protein: 3.3, fat: 0.4, carbs: 6.1, fiber: 2.3, tag: 'veggie' },
  { name: 'Nấm linh chi nâu', nameEn: 'Brown beech mushroom', calories: 35, protein: 2.7, fat: 0.4, carbs: 6.4, fiber: 2.5, tag: 'veggie' },
  { name: 'Nấm portobello', nameEn: 'Portobello mushroom', calories: 22, protein: 2.1, fat: 0.4, carbs: 3.9, fiber: 1.3, tag: 'veggie' },
  { name: 'Cải thìa (Cải chip)', nameEn: 'Bok choy / Pak choi', calories: 13, protein: 1.5, fat: 0.2, carbs: 2.2, fiber: 1, tag: 'veggie' },
  { name: 'Cải làn (Cải rổ)', nameEn: 'Chinese broccoli / Gai lan', calories: 25, protein: 2, fat: 0.3, carbs: 3.5, fiber: 2.2, tag: 'veggie' },
  { name: 'Củ năng', nameEn: 'Water chestnut', calories: 97, protein: 1.4, fat: 0.1, carbs: 23.9, fiber: 3, tag: 'veggie' },
  { name: 'Bông bí (Hoa bí)', nameEn: 'Pumpkin flower', calories: 15, protein: 1, fat: 0.1, carbs: 3.3, fiber: 1.1, tag: 'veggie' },
  { name: 'Đậu ván (quả)', nameEn: 'Hyacinth bean pods', calories: 49, protein: 2.9, fat: 0.2, carbs: 9, fiber: 2, tag: 'veggie' },
  { name: 'Nấm tuyết (Ngân nhĩ) khô', nameEn: 'Snow fungus / White jelly mushroom, dried', calories: 200, protein: 4.6, fat: 0.5, carbs: 73, fiber: 30, tag: 'veggie' },
  { name: 'Mầm đá (Cải mầm đá Sapa)', nameEn: 'Sapa stone mustard sprout', calories: 25, protein: 2.5, fat: 0.3, carbs: 3.5, fiber: 2.2, tag: 'veggie' },
  { name: 'Rau tề thái', nameEn: "Shepherd's purse", calories: 31, protein: 4.2, fat: 0.5, carbs: 4.3, fiber: 2, tag: 'veggie' },
  { name: 'Rau bợ', nameEn: 'Water clover', calories: 22, protein: 2, fat: 0.2, carbs: 3, fiber: 1.8, tag: 'veggie' },
  { name: 'Rau tầm bóp', nameEn: 'Ground cherry / Physalis leaves', calories: 30, protein: 1.9, fat: 0.7, carbs: 5, fiber: 1.7, tag: 'veggie' },
  { name: 'Củ kiệu muối', nameEn: 'Pickled scallion bulb', calories: 50, protein: 1.5, fat: 0.2, carbs: 11, fiber: 2, tag: 'veggie' },
  { name: 'Dưa cải muối chua', nameEn: 'Pickled mustard greens', calories: 19, protein: 1.5, fat: 0.3, carbs: 2.5, fiber: 1.8, tag: 'veggie' },
  { name: 'Cà pháo muối', nameEn: 'Pickled Thai eggplant', calories: 28, protein: 1.3, fat: 0.2, carbs: 5.5, fiber: 3, tag: 'veggie' },
  { name: 'Dưa giá', nameEn: 'Pickled bean sprouts', calories: 28, protein: 3, fat: 0.2, carbs: 4, fiber: 1.8, tag: 'veggie' },
  { name: 'Kim chi', nameEn: 'Kimchi', calories: 23, protein: 1.6, fat: 0.5, carbs: 4, fiber: 1.6, tag: 'veggie' },
  { name: 'Rong nho', nameEn: 'Sea grapes', calories: 24, protein: 1, fat: 0.3, carbs: 5, fiber: 1.2, tag: 'veggie' },
  { name: 'Rong biển wakame (tươi)', nameEn: 'Wakame seaweed, fresh', calories: 45, protein: 3, fat: 0.6, carbs: 9.1, fiber: 0.5, tag: 'veggie' },
  { name: 'Tảo bẹ (Kombu)', nameEn: 'Kombu / Kelp', calories: 43, protein: 1.7, fat: 0.6, carbs: 9.6, fiber: 1, tag: 'veggie' },
  { name: 'Rong biển lá khô (Nori)', nameEn: 'Nori seaweed, dried sheet', calories: 35, protein: 5.8, fat: 0.3, carbs: 5.1, fiber: 0.3, tag: 'veggie' },
  { name: 'Rau mầm (chung)', nameEn: 'Mixed microgreens', calories: 30, protein: 3, fat: 0.4, carbs: 4, fiber: 1.9, tag: 'veggie' },
  { name: 'Mầm súp lơ xanh', nameEn: 'Broccoli sprouts', calories: 35, protein: 3, fat: 0.5, carbs: 5, fiber: 2.5, tag: 'veggie' },
  { name: 'Mầm củ cải', nameEn: 'Radish sprouts', calories: 43, protein: 3.8, fat: 2.5, carbs: 3.6, fiber: 1.8, tag: 'veggie' },
  { name: 'Mầm đậu Hà Lan', nameEn: 'Pea sprouts / Pea shoots', calories: 42, protein: 4, fat: 0.4, carbs: 6.5, fiber: 2.5, tag: 'veggie' },
  { name: 'Giá đậu nành', nameEn: 'Soybean sprouts', calories: 122, protein: 13.1, fat: 6.7, carbs: 9.6, fiber: 1, tag: 'veggie' },
  { name: 'Mầm cỏ linh lăng', nameEn: 'Alfalfa sprouts', calories: 23, protein: 4, fat: 0.7, carbs: 2.1, fiber: 1.9, tag: 'veggie' },
  { name: 'Táo đỏ nhập (Chung)', nameEn: 'Imported Red Apple', calories: 52, protein: 0.3, fat: 0.2, carbs: 13.8, fiber: 2.4, tag: 'fruit' },
  { name: 'Thanh long', nameEn: 'Dragon Fruit', calories: 60, protein: 1.2, fat: 0.6, carbs: 12.9, fiber: 2.9, tag: 'fruit' },
  { name: 'Vải', nameEn: 'Litchi; lychee', calories: 45, protein: 0.71, fat: 0.43, carbs: 9.61, fiber: 1.3, tag: 'fruit' },
  { name: 'Xoài xanh (ương)', nameEn: 'Semi-ripe Mango', calories: 65, protein: 0.5, fat: 0.3, carbs: 16, fiber: 1.6, tag: 'fruit' },
  { name: 'Xoài chín vừa', nameEn: 'Ripe Mango', calories: 60, protein: 0.8, fat: 0.4, carbs: 15, fiber: 1.6, tag: 'fruit' },
  { name: 'Xoài chín kĩ', nameEn: 'Overripe Mango', calories: 70, protein: 0.7, fat: 0.4, carbs: 17.5, fiber: 1.6, tag: 'fruit' },
  { name: 'Chuối tiêu', nameEn: 'Banana, dwarf', calories: 97, protein: 1.51, fat: 0.21, carbs: 22.21, fiber: 2.6, tag: 'fruit' },
  { name: 'Chuối lá', nameEn: 'Saba Banana', calories: 105, protein: 1.2, fat: 0.2, carbs: 27, fiber: 3, tag: 'fruit' },
  { name: 'Chôm chôm', nameEn: 'Rambutan', calories: 72, protein: 1.51, fat: 0.01, carbs: 16.41, fiber: 0.9, tag: 'fruit' },
  { name: 'Dưa vàng', nameEn: 'Cantaloupe', calories: 34, protein: 0.8, fat: 0.2, carbs: 8.2, fiber: 0.9, tag: 'fruit' },
  { name: 'Ổi', nameEn: 'Guava, common', calories: 38, protein: 0.61, fat: 1.03, carbs: 6.81, fiber: 5.4, tag: 'fruit' },
  { name: 'Kiwi', nameEn: 'Kiwi', calories: 61, protein: 1.1, fat: 0.5, carbs: 14.7, fiber: 3, tag: 'fruit' },
  { name: 'Na', nameEn: 'Sugarapple, sweetsop', calories: 66, protein: 1.61, fat: 0.33, carbs: 14.21, fiber: 4.4, tag: 'fruit' },
  { name: 'Nhãn', nameEn: 'Longan', calories: 48, protein: 0.91, fat: 0.13, carbs: 10.91, fiber: 1.1, tag: 'fruit' },
  { name: 'Quả bơ', nameEn: 'Avocado', calories: 160, protein: 2, fat: 14.7, carbs: 8.5, fiber: 6.7, tag: 'fruit' },
  { name: 'Quýt', nameEn: 'Tangerine; Orange; Mandarin', calories: 39, protein: 0.81, fat: 0.33, carbs: 8.31, fiber: 1.8, tag: 'fruit' },
  { name: 'Lê', nameEn: 'Pear', calories: 45, protein: 0.71, fat: 0.21, carbs: 10.21, fiber: 3.1, tag: 'fruit' },
  { name: 'Mận', nameEn: 'Japanese, plum', calories: 20, protein: 0.61, fat: 0.21, carbs: 3.91, fiber: 1.4, tag: 'fruit' },
  { name: 'Nho đỏ', nameEn: 'Red Grapes', calories: 69, protein: 0.7, fat: 0.2, carbs: 18.1, fiber: 0.9, tag: 'fruit' },
  { name: 'Nho xanh', nameEn: 'Green Grapes', calories: 69, protein: 0.7, fat: 0.2, carbs: 18.1, fiber: 0.9, tag: 'fruit' },
  { name: 'Nho đen', nameEn: 'Black Grapes', calories: 70, protein: 0.6, fat: 0.3, carbs: 18.2, fiber: 0.9, tag: 'fruit' },
  { name: 'Quả mâm xôi', nameEn: 'Raspberry', calories: 52, protein: 1.2, fat: 0.7, carbs: 11.9, fiber: 6.5, tag: 'fruit' },
  { name: 'Bưởi diễn', nameEn: 'Diển Pomelo', calories: 38, protein: 0.6, fat: 0.1, carbs: 9.2, fiber: 1, tag: 'fruit' },
  { name: 'Bưởi da xanh', nameEn: 'Green-skinned Pomelo', calories: 42, protein: 0.8, fat: 0.1, carbs: 10.4, fiber: 1, tag: 'fruit' },
  { name: 'Dưa hấu', nameEn: 'Watermelon', calories: 16, protein: 1.21, fat: 0.21, carbs: 2.31, fiber: 0.4, tag: 'fruit' },
  { name: 'Đu đủ', nameEn: 'Papaya', calories: 43, protein: 0.5, fat: 0.3, carbs: 10.8, fiber: 1.7, tag: 'fruit' },
  { name: 'Dâu tây', nameEn: 'Strawberry', calories: 43, protein: 1.81, fat: 0.41, carbs: 8.11, fiber: 2, tag: 'fruit' },
  { name: 'Khế', nameEn: 'Carambola; Star fruit', calories: 16, protein: 0.61, fat: 0.33, carbs: 2.81, fiber: 2.8, tag: 'fruit' },
  { name: 'Sầu riêng', nameEn: 'Durian, Civet', calories: 132, protein: 2.51, fat: 1.61, carbs: 26.91, fiber: 3.8, tag: 'fruit' },
  { name: 'Trái cóc', nameEn: 'Ambarella', calories: 46, protein: 0.5, fat: 0.1, carbs: 10.5, fiber: 2.2, tag: 'fruit' },
  { name: 'Gạo nếp máy (loại thường)', nameEn: 'Glutinous rice, milled', calories: 346, protein: 8.42, fat: 1.62, carbs: 74.92, tag: 'starch' },
  { name: 'Gạo tẻ giã', nameEn: 'Under milled, home-pounded rice', calories: 344, protein: 8.11, fat: 1.31, carbs: 75.01, tag: 'starch' },
  { name: 'Gạo tẻ máy', nameEn: 'Ordinary polished rice', calories: 344, protein: 7.91, fat: 1.01, carbs: 75.91, tag: 'starch' },
  { name: 'Gạo lứt', nameEn: 'Rice, brown or hulled', calories: 345, protein: 7.53, fat: 2.73, carbs: 72.83, tag: 'starch' },
  { name: 'Kê', nameEn: 'Foxtail millet', calories: 331, protein: 7.01, fat: 3.01, carbs: 69.01, tag: 'starch' },
  { name: 'Ngô bắp tươi', nameEn: 'Fresh maize seeds, raw', calories: 196, protein: 4.11, fat: 2.31, carbs: 39.61, fiber: 2.7, tag: 'veggie' },
  { name: 'Ngô vàng hạt khô', nameEn: 'Yellow maize, dried seeds', calories: 354, protein: 8.61, fat: 4.71, carbs: 69.41, fiber: 7.3, tag: 'starch' },
  { name: 'Bánh bao', nameEn: 'Ball shaped dumpling, Vietnamese steamed buns', calories: 219, protein: 6.11, fat: 0.51, carbs: 47.51, tag: 'meal' },
  { name: 'Bún riêu cua cỡ vừa', nameEn: 'Rieu Noodle', calories: 482, protein: 10.2, fat: 4.2, carbs: 55, tag: 'meal' },
  { name: 'Bún bò Huế cỡ vừa', nameEn: 'Hue Beef Noodle', calories: 534, protein: 24.5, fat: 15.2, carbs: 58.3, tag: 'meal' },
  { name: 'Bún chả Hà Nội (1 suất)', nameEn: 'Hanoi Grilled Pork Noodle', calories: 580, protein: 26.1, fat: 20.4, carbs: 62.5, tag: 'meal' },
  { name: 'Bún mọc sườn dọc mùng', nameEn: 'Pork Ball and Rib Noodle', calories: 465, protein: 21.8, fat: 11.5, carbs: 54.2, tag: 'meal' },
  { name: 'Bún thang Hà Nội', nameEn: 'Hanoi Combination Noodle', calories: 415, protein: 22.3, fat: 8.5, carbs: 52.0, tag: 'meal' },
  { name: 'Bún mắm miền Tây', nameEn: 'Western Fermented Fish Noodle', calories: 495, protein: 23.0, fat: 9.8, carbs: 60.4, tag: 'meal' },
  { name: 'Bún hải sản chua cay', nameEn: 'Spicy Seafood Noodle', calories: 440, protein: 25.6, fat: 7.2, carbs: 53.5, tag: 'meal' },
  { name: 'Bún cá rô đồng', nameEn: 'Field Catfish Noodle', calories: 420, protein: 20.4, fat: 8.1, carbs: 55.2, tag: 'meal' },
  { name: 'Bún thịt nướng miền Nam', nameEn: 'Southern Grilled Pork Noodle', calories: 553, protein: 22.5, fat: 18.2, carbs: 63.8, tag: 'meal' },
  { name: 'Bún đậu mắm tôm (suất cơ bản)', nameEn: 'Tofu Fried with Shrimp Paste Noodle', calories: 510, protein: 18.5, fat: 19.0, carbs: 57.4, tag: 'meal' },
  { name: 'Bún xào thịt bò', nameEn: 'Stir-fried Beef Noodle', calories: 498, protein: 24.2, fat: 12.5, carbs: 56.0, tag: 'meal' },
  { name: 'Cơm tấm sườn nướng', nameEn: 'Broken Rice with Grilled Pork Chop', calories: 595, protein: 28.4, fat: 18.2, carbs: 67.5, tag: 'meal' },
  { name: 'Cơm gà Hội An', nameEn: 'Hoi An Chicken Rice', calories: 548, protein: 26.5, fat: 14.1, carbs: 65.2, tag: 'meal' },
  { name: 'Cơm rang dưa bò', nameEn: 'Fried Rice with Beef and Pickled Mustard', calories: 632, protein: 24.8, fat: 20.5, carbs: 74.0, tag: 'meal' },
  { name: 'Cơm đùi gà nướng mật ong', nameEn: 'Rice with Honey Grilled Chicken Thigh', calories: 585, protein: 31.2, fat: 16.4, carbs: 66.0, tag: 'meal' },
  { name: 'Cơm thịt kho tàu (suất bình dân)', nameEn: 'Rice with Braised Pork and Eggs', calories: 615, protein: 22.3, fat: 24.1, carbs: 64.8, tag: 'meal' },
  { name: 'Cơm cá kho tộ', nameEn: 'Rice with Claypot Braised Fish', calories: 490, protein: 25.6, fat: 10.2, carbs: 63.5, tag: 'meal' },
  { name: 'Cơm rang cải xanh', nameEn: 'Rice with Stir-fried Beef and Broccoli', calories: 485, protein: 27.4, fat: 11.0, carbs: 61.2, tag: 'meal' },
  { name: 'Bánh mì kẹp thịt chả truyền thống', nameEn: 'Traditional Pork and Ham Banh Mi', calories: 425, protein: 14.8, fat: 16.5, carbs: 51.2, tag: 'meal' },
  { name: 'Bánh mì xíu mại', nameEn: 'Banh Mi with Pork Meatballs', calories: 395, protein: 13.5, fat: 15.0, carbs: 49.5, tag: 'meal' },
  { name: 'Bánh mì heo quay', nameEn: 'Roasted Pork Belly Banh Mi', calories: 485, protein: 16.2, fat: 22.4, carbs: 51.0, tag: 'meal' },
  { name: 'Bánh mì chả cá', nameEn: 'Fried Fish Cake Banh Mi', calories: 380, protein: 15.1, fat: 12.6, carbs: 48.8, tag: 'meal' },
  { name: 'Bánh mì gà xé', nameEn: 'Shredded Chicken Banh Mi', calories: 365, protein: 18.4, fat: 9.8, carbs: 48.0, tag: 'meal' },
  { name: 'Bánh mì trứng ốp la (2 quả)', nameEn: 'Banh Mi with Double Fried Eggs', calories: 392, protein: 15.2, fat: 16.0, carbs: 44.5, tag: 'meal' },
  { name: 'Bánh mì bò né (1 suất)', nameEn: 'Sizzling Beef Banh Mi Platter', calories: 560, protein: 28.5, fat: 24.2, carbs: 53.0, tag: 'meal' },
  { name: 'Bánh mì paté chà bông', nameEn: 'Pate and Pork Floss Banh Mi', calories: 410, protein: 12.8, fat: 17.5, carbs: 47.6, tag: 'meal' },
  { name: 'Bánh mì sốt vang (1 suất)', nameEn: 'Beef Stew with Banh Mi', calories: 515, protein: 24.6, fat: 18.0, carbs: 59.5, tag: 'meal' },
  { name: 'Bánh mì Doner Kebab', nameEn: 'Doner Kebab Banh Mi', calories: 415, protein: 18.2, fat: 15.6, carbs: 50.5, tag: 'meal' },
  { name: 'Bánh đa nem', nameEn: 'Rice paper for rollers', calories: 333, protein: 4.01, fat: 0.21, carbs: 78.91, tag: 'starch' },
  { name: 'Bánh đúc', nameEn: 'Rice pudding', calories: 52, protein: 0.91, fat: 0.31, carbs: 11.31, tag: 'meal' },
  { name: 'Bánh mỳ', nameEn: 'French bread', calories: 249, protein: 7.91, fat: 0.81, carbs: 52.61, tag: 'starch' },
  { name: 'Bánh phở', nameEn: 'Rice noodles', calories: 143, protein: 3.21, fat: 0.43, carbs: 31.71, tag: 'starch' },
  { name: 'Bánh quẩy', nameEn: 'Wheat fritters twisted fried', calories: 292, protein: 8.01, fat: 10.81, carbs: 40.71, tag: 'junk' },
  { name: 'Bánh ngô', nameEn: 'Corn flakes', calories: 372, protein: 8.61, fat: 1.61, carbs: 80.81, tag: 'junk' },
  { name: 'Bột gạo nếp', nameEn: 'Glutinous rice flour', calories: 362, protein: 8.21, fat: 1.61, carbs: 78.81, tag: 'starch' },
  { name: 'Bột gạo tẻ', nameEn: 'Rice ordinary flour', calories: 359, protein: 6.61, fat: 0.41, carbs: 82.21, tag: 'starch' },
  { name: 'Bột mì', nameEn: 'Wheat flour', calories: 346, protein: 10.31, fat: 1.11, carbs: 73.61, tag: 'starch' },
  { name: 'Bột ngô vàng', nameEn: 'Yellow maize flour', calories: 361, protein: 8.31, fat: 4.01, carbs: 73.01, tag: 'starch' },
  { name: 'Bún', nameEn: 'Rice vermicelli', calories: 110, protein: 1.71, fat: 0, carbs: 25.71, tag: 'starch' },
  { name: 'Cốm', nameEn: 'Rice, unriped. Raw', calories: 297, protein: 6.11, fat: 0.81, carbs: 66.31, tag: 'starch' },
  { name: 'Mỳ sợi', nameEn: 'Wheat noodles', calories: 349, protein: 11.01, fat: 0.91, carbs: 74.21, tag: 'starch' },
  { name: 'Ngô nếp luộc', nameEn: 'Glutinous maize, boiled', calories: 167, protein: 3.91, fat: 2.21, carbs: 32.91, tag: 'starch' },
  { name: 'Củ ấu', nameEn: 'Water-caltrops', calories: 115, protein: 3.61, fat: 0.51, carbs: 24.01, tag: 'veggie' },
  { name: 'Củ cái', nameEn: 'Yam winged', calories: 127, protein: 3.11, fat: 0.23, carbs: 28.31, tag: 'veggie' },
  { name: 'Củ dong', nameEn: 'Bermuda tuber', calories: 119, protein: 1.41, fat: 0, carbs: 28.41, tag: 'veggie' },
  { name: 'Củ sắn', nameEn: 'Bitter cassava', calories: 152, protein: 1.11, fat: 0.21, carbs: 36.41, tag: 'veggie' },
  { name: 'Củ sắn dây', nameEn: 'Radix puerariae', calories: 119, protein: 1.61, fat: 0.11, carbs: 28.01, tag: 'veggie' },
  { name: 'Củ súng khô (đã bỏ vỏ)', nameEn: 'Nymphaea stellata wild, dried, unshelled', calories: 350, protein: 16.11, fat: 0.51, carbs: 70.31, tag: 'veggie' },
  { name: 'Củ từ', nameEn: 'Igname Yam, Chinese', calories: 92, protein: 1.51, fat: 0, carbs: 21.51, tag: 'veggie' },
  { name: 'Miến dong', nameEn: 'Vermicelli from Bermuda tuber', calories: 332, protein: 0.61, fat: 0.11, carbs: 82.21, tag: 'starch' },
  { name: 'Bột dong lọc', nameEn: 'Bermuda flour', calories: 341, protein: 0.61, fat: 0, carbs: 84.71, tag: 'starch' },
  { name: 'Bột khoai lang', nameEn: 'Sweet potato flour', calories: 334, protein: 2.21, fat: 0.51, carbs: 80.21, tag: 'starch' },
  { name: 'Bột khoai riềng (bột đao)', nameEn: 'Canna edulis Ker, flour', calories: 337, protein: 0.21, fat: 0, carbs: 84.11, tag: 'starch' },
  { name: 'Bột khoai tây (lọc)', nameEn: 'Potato flour, white', calories: 345, protein: 1.01, fat: 0.33, carbs: 84.41, tag: 'starch' },
  { name: 'Bột sắn', nameEn: 'Cassava flour', calories: 333, protein: 2.41, fat: 0.51, carbs: 79.61, tag: 'starch' },
  { name: 'Bột sắn dây', nameEn: 'Radix puerariae flour', calories: 340, protein: 0.71, fat: 0, carbs: 84.31, tag: 'starch' },
  { name: 'Khoai tây lát chiên', nameEn: 'Potato crisp, fried', calories: 525, protein: 2.21, fat: 35.41, carbs: 49.31, tag: 'junk' },
  { name: 'Sắn khô', nameEn: 'Dried bitter cassava', calories: 340, protein: 3.01, fat: 0.71, carbs: 80.31, tag: 'starch' },
  { name: 'Trân châu sắn', nameEn: 'Tapioca, pearls E.P', calories: 341, protein: 1.01, fat: 0, carbs: 84.31, tag: 'junk' },
  { name: 'Đậu cô ve (hạt)', nameEn: 'French bean seeds, dried', calories: 321, protein: 21.81, fat: 1.61, carbs: 54.91, tag: 'starch' },
  { name: 'Đậu đen (hạt)', nameEn: 'Black bean seeds, dried', calories: 325, protein: 24.21, fat: 1.71, carbs: 53.31, tag: 'starch' },
  { name: 'Đậu đũa (hạt)', nameEn: 'Cow pea whole seeds, dried', calories: 320, protein: 23.71, fat: 2.01, carbs: 51.91, tag: 'starch' },
  { name: 'Đậu Hà Lan (hạt)', nameEn: 'Peas garden and field, seeds, dried', calories: 318, protein: 22.21, fat: 1.41, carbs: 54.11, tag: 'starch' },
  { name: 'Đậu tương (đậu nành)', nameEn: 'Yellow dried soybean seeds, dried', calories: 400, protein: 34.01, fat: 18.41, carbs: 24.61, tag: 'protein' },
  { name: 'Đậu trắng hạt (Đậu Tây)', nameEn: 'Kidney bean whole seeds, dried', calories: 327, protein: 23.21, fat: 2.11, carbs: 53.81, tag: 'starch' },
  { name: 'Đậu trứng cuốc', nameEn: 'Egg bird bean seeds, dried', calories: 321, protein: 25.81, fat: 2.01, carbs: 50.01, tag: 'starch' },
  { name: 'Đậu xanh (đậu tắt)', nameEn: 'Mungo bean seeds, dried', calories: 328, protein: 23.41, fat: 2.41, carbs: 53.11, tag: 'starch' },
  { name: 'Chestnut, Chinese whole, raw', nameEn: 'Chestnut, Chinese whole, raw', calories: 638, protein: 18.01, fat: 59.01, carbs: 8.71, tag: 'fat' },
  { name: 'Hạt dẻ tươi', nameEn: 'Chestnut, Chinese whole, raw', calories: 223, protein: 4.23, fat: 1.13, carbs: 49.13, tag: 'starch' },
  { name: 'Hạt dẻ khô', nameEn: 'Chestnut, dried', calories: 363, protein: 6.83, fat: 1.83, carbs: 79.83, tag: 'starch' },
  { name: 'Hạt đen', nameEn: 'Black seed', calories: 472, protein: 17.31, fat: 29.01, carbs: 35.51, tag: 'fat' },
  { name: 'Hạt điều', nameEn: 'Cashew nut, common', calories: 605, protein: 18.41, fat: 46.31, carbs: 28.71, tag: 'fat' },
  { name: 'Hạt mít', nameEn: 'Jack fruit, seed, raw', calories: 166, protein: 0.71, fat: 1.11, carbs: 38.31, tag: 'starch' },
  { name: 'Lạc hạt', nameEn: 'Dried peanut seed', calories: 573, protein: 27.51, fat: 44.51, carbs: 15.51, tag: 'fat' },
  { name: 'Quả cọ tươi', nameEn: 'Palm fruit fresh', calories: 178, protein: 2.31, fat: 13.41, carbs: 12.11, tag: 'fat' },
  { name: 'Quả đại hái tươi', nameEn: 'Hodgsonia fruit', calories: 427, protein: 20.01, fat: 38.01, carbs: 1.21, tag: 'fat' },
  { name: 'Vừng (đen, trắng)', nameEn: 'Sesame oriental seeds, whole, dried black or white', calories: 568, protein: 20.11, fat: 46.41, carbs: 17.61, tag: 'fat' },
  { name: 'Bột đậu tương đã loại béo (đậu nành)', nameEn: 'Soybeans flour, defatted', calories: 321, protein: 49.01, fat: 1.01, carbs: 29.01, tag: 'protein' },
  { name: 'Bột đậu tương rang chín', nameEn: 'Roasted soybeans flour', calories: 418, protein: 41.01, fat: 18.01, carbs: 22.91, tag: 'protein' },
  { name: 'Bột đậu xanh', nameEn: 'Mungo bean flour', calories: 347, protein: 24.61, fat: 2.51, carbs: 56.51, tag: 'starch' },
  { name: 'Bột lạc', nameEn: 'Peanut flour', calories: 575, protein: 27.51, fat: 45.01, carbs: 15.01, tag: 'fat' },
  { name: 'Đậu phụ chúc', nameEn: 'Curd tofu concentrated', calories: 414, protein: 50.21, fat: 20.81, carbs: 6.51, tag: 'protein' },
  { name: 'Hạt bí đỏ rang', nameEn: 'Pumpkin seeds, fried', calories: 519, protein: 35.11, fat: 31.81, carbs: 23.01, tag: 'fat' },
  { name: 'Hạt dưa đỏ rang (dưa hấu)', nameEn: 'Water melon seeds whole, fried', calories: 551, protein: 31.81, fat: 39.11, carbs: 18.01, tag: 'fat' },
  { name: 'Hạt điều khô, chiên dầu', nameEn: 'Cashew, common, roasted with oil', calories: 583, protein: 18.31, fat: 49.31, carbs: 16.41, tag: 'junk' },
  { name: 'Sữa bột đậu nành', nameEn: 'Milk flour, made from roasted soybeans', calories: 405, protein: 31.11, fat: 9.71, carbs: 48.21, tag: 'protein' },
  { name: 'Sữa đậu nành (100g đậu/lít)', nameEn: 'Soybean milk (100 g soybean/l)', calories: 28, protein: 3.11, fat: 1.61, carbs: 0.41, tag: 'protein' },
  { name: 'Tào phớ', nameEn: 'Tofu in light syrup (Tofu 160g, sirup 65ml)', calories: 37, protein: 2.31, fat: 0.21, carbs: 6.41, tag: 'meal' },
  { name: 'Rau câu khô', nameEn: 'Dried seaweed', calories: 198, protein: 11.21, fat: 1.11, carbs: 35.81, tag: 'veggie' },
  { name: 'Hạt sen tươi', nameEn: 'Lotus seed, raw', calories: 161, protein: 9.51, fat: 0.53, carbs: 29.51, tag: 'starch' },
  { name: 'Hạt sen khô', nameEn: 'Dried lotus seed', calories: 334, protein: 20.01, fat: 2.41, carbs: 58.01, tag: 'starch' },
  { name: 'Men bia khô', nameEn: "Brewer's yeast, fried", calories: 340, protein: 52.51, fat: 3.21, carbs: 25.41, tag: 'protein' },
  { name: 'Men bia tươi', nameEn: "Baker's yeast, fresh", calories: 95, protein: 16.21, fat: 1.31, carbs: 4.51, tag: 'protein' },
  { name: 'Mộc nhĩ', nameEn: "Jew's ear, Juda's ear, dried, Wood-ear, Tender variety", calories: 304, protein: 10.61, fat: 0.21, carbs: 65.01, tag: 'veggie' },
  { name: 'Nấm hương khô', nameEn: 'Mushroom Chinese, dried', calories: 274, protein: 36.01, fat: 4.01, carbs: 23.51, tag: 'veggie' },
  { name: 'Nấm hương tươi', nameEn: 'Mushroom, Chinese, raw', calories: 39, protein: 5.51, fat: 0.51, carbs: 3.11, tag: 'veggie' },
  { name: 'Nấm mỡ (Nấm tây)', nameEn: 'Mushroom', calories: 32, protein: 4.01, fat: 0.31, carbs: 3.41, tag: 'veggie' },
  { name: 'Nấm rơm', nameEn: 'Mushroom, straw', calories: 57, protein: 3.61, fat: 3.21, carbs: 3.41, tag: 'veggie' },
  { name: 'Nấm thường tươi', nameEn: 'Mushroom, common', calories: 34, protein: 4.61, fat: 0.81, carbs: 2.21, tag: 'veggie' },
  { name: 'Mỡ lợn muối', nameEn: 'Lard, salted', calories: 827, protein: 2.01, fat: 91.01, carbs: 0.01, tag: 'fat' },
  { name: 'Mỡ lợn nước', nameEn: 'Lard, liquid', calories: 896, protein: 0.01, fat: 99.61, carbs: 0.01, tag: 'fat' },
  { name: 'Bơ thực vật', nameEn: 'Butter-margarine blend, stick, unsalted', calories: 729, protein: 0.53, fat: 80.73, carbs: 0.13, tag: 'fat' },
  { name: 'Dầu bông', nameEn: 'Cottonseed oil, salad or cooking', calories: 900, protein: 0.03, fat: 100.03, carbs: 0.03, tag: 'fat' },
  { name: 'Dầu cám gạo', nameEn: 'Rice bran oil', calories: 900, protein: 0.03, fat: 100.03, carbs: 0.03, tag: 'fat' },
  { name: 'Dầu cọ', nameEn: 'Palm oil', calories: 900, protein: 0.03, fat: 100.03, carbs: 0.03, tag: 'fat' },
  { name: 'Dầu dừa', nameEn: 'Coconut oil', calories: 900, protein: 0.03, fat: 100.03, carbs: 0.03, tag: 'fat' },
  { name: 'Dầu đậu tương', nameEn: 'Soybean oil, salad or cooking', calories: 900, protein: 0.03, fat: 100.03, carbs: 0.03, tag: 'fat' },
  { name: 'Dầu lạc', nameEn: 'Peanut oil, salad or cooking', calories: 900, protein: 0.03, fat: 100.03, carbs: 0.03, tag: 'fat' },
  { name: 'Dầu mì', nameEn: 'Sesame oil, salad or cooking', calories: 900, protein: 0.03, fat: 100.03, carbs: 0.03, tag: 'fat' },
  { name: 'Dầu ngô', nameEn: 'Corn oil, salad or cooking', calories: 900, protein: 0.03, fat: 100.03, carbs: 0.03, tag: 'fat' },
  { name: 'Dầu oliu', nameEn: 'Olive oil, salad or cooking', calories: 900, protein: 0.03, fat: 100.03, carbs: 0.03, tag: 'fat' },
  { name: 'Thịt bê mỡ', nameEn: 'Veal meat, lean and fat', calories: 144, protein: 19.01, fat: 7.51, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt bê nạc', nameEn: 'Veal meat, lean only', calories: 85, protein: 20.01, fat: 0.51, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt bò loại I', nameEn: 'Beef, grade I', calories: 118, protein: 21.01, fat: 3.81, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt bò loại II', nameEn: 'Beef, grade II', calories: 167, protein: 18.01, fat: 10.51, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt bò, lưng, nạc', nameEn: 'Beef, top loin, seperable lean only, trimmed to 1/8" fat, prime, raw', calories: 127, protein: 23.13, fat: 3.93, carbs: 0.03, tag: 'protein' },
  { name: 'Thịt bò, lưng, nạc và mỡ', nameEn: 'Beef, top loin, seperable lean only, trimmed to 1/4" fat, prime, raw', calories: 182, protein: 21.53, fat: 10.73, carbs: 0.03, tag: 'protein' },
  { name: 'Đùi gà không da, không xương', nameEn: 'Chicken, Thigh, Skinless, Boneless', calories: 130, protein: 20, fat: 5, carbs: 0, tag: 'protein' },
  { name: 'Đùi gà có da, không xương', nameEn: 'Chicken, Thigh, Boneless', calories: 170, protein: 18, fat: 10, carbs: 0, tag: 'protein' },
  { name: 'Đùi gà có da, có xương', nameEn: 'Chicken, Thigh', calories: 150, protein: 16.2, fat: 10, carbs: 0, tag: 'protein' },
  { name: 'Ức gà không da, không xương', nameEn: 'Chicken, Breast, Skinless, Boneless', calories: 120, protein: 23.6, fat: 1.9, carbs: 0, tag: 'protein' },
  { name: 'Ức gà có da, không xương', nameEn: 'Chicken, Breast, Boneless', calories: 157, protein: 21.5, fat: 7.3, carbs: 0, tag: 'protein' },
  { name: 'Ức gà có da, có xương', nameEn: 'Chicken, Breast, Bone-in', calories: 157, protein: 18, fat: 6.5, carbs: 0, tag: 'protein' },
  { name: 'Thịt lợn vai giòn', nameEn: 'Pork, Shoulder, Crisp Lean', calories: 145, protein: 20.0, fat: 6.5, carbs: 0, tag: 'protein' },
  { name: 'Rẻ sườn lợn', nameEn: 'Pork, Ribs (Meat only)', calories: 247, protein: 16.5, fat: 19.2, carbs: 0, tag: 'protein' },
  { name: 'Ba chỉ lợn', nameEn: 'Pork, Belly', calories: 285, protein: 15.8, fat: 24.0, carbs: 0, tag: 'protein' },
  { name: 'Thịt mông lợn', nameEn: 'Pork, Rump (Lean)', calories: 125, protein: 21.0, fat: 4.2, carbs: 0, tag: 'protein' },
  { name: 'Thịt lợn má đào', nameEn: 'Pork, Inner Jowl Meat', calories: 162, protein: 18.2, fat: 9.8, carbs: 0, tag: 'protein' },
  { name: 'Ba chỉ bò', nameEn: 'Beef, Short Plate', calories: 260, protein: 16.0, fat: 21.5, carbs: 0, tag: 'protein' },
  { name: 'Bắp bò', nameEn: 'Beef, Shank', calories: 135, protein: 21.4, fat: 4.8, carbs: 0, tag: 'protein' },
  { name: 'Lõi rùa bò', nameEn: 'Beef, Heel Muscle', calories: 142, protein: 20.5, fat: 6.2, carbs: 0, tag: 'protein' },
  { name: 'Thăn bò', nameEn: 'Beef, Loin (Tenderloin)', calories: 136, protein: 22.3, fat: 4.6, carbs: 0, tag: 'protein' },
  { name: 'Gầu bò', nameEn: 'Beef, Brisket (Fatty cut)', calories: 254, protein: 16.2, fat: 20.5, carbs: 0, tag: 'protein' },
  { name: 'Nạm bò', nameEn: 'Beef, Flank', calories: 192, protein: 18.5, fat: 12.4, carbs: 0, tag: 'protein' },
  { name: 'Thịt bồ câu ra ràng', nameEn: 'Pigeon young bird flesh skin and giblets', calories: 340, protein: 17.51, fat: 30.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt chó sấn', nameEn: 'Dog meat', calories: 338, protein: 16.01, fat: 30.41, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt chó vai', nameEn: 'Dog, shoulder', calories: 230, protein: 18.01, fat: 17.61, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt cừu, nạc', nameEn: 'Mutton meat, lean', calories: 219, protein: 16.41, fat: 17.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt dê, nạc', nameEn: 'Goat, meat, lean', calories: 122, protein: 20.71, fat: 4.31, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt gà rừng', nameEn: 'Grouse field chicken', calories: 141, protein: 24.41, fat: 4.81, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt gà ta', nameEn: 'Chicken meat, average', calories: 199, protein: 20.31, fat: 13.11, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt gà tây', nameEn: 'Turkey raw flesh and skin giblets', calories: 218, protein: 20.11, fat: 15.31, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt hươu', nameEn: 'Deer meat', calories: 94, protein: 19.01, fat: 2.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt lợn mỡ', nameEn: 'Pork, lean and fat', calories: 394, protein: 14.51, fat: 37.31, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt lợn nạc', nameEn: 'Pork, lean', calories: 139, protein: 19.01, fat: 7.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt lợn nửa nạc, nửa mỡ', nameEn: 'Pork, medium fat', calories: 260, protein: 16.51, fat: 21.51, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt ngỗng', nameEn: 'Goose', calories: 409, protein: 14.01, fat: 39.21, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt ngựa', nameEn: 'Horse meat', calories: 176, protein: 21.51, fat: 10.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt thỏ nhà', nameEn: 'Rabbit meat, raw', calories: 158, protein: 21.51, fat: 8.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt thỏ rừng', nameEn: 'Hare rabbit (field or wild)', calories: 103, protein: 23.51, fat: 1.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt trâu', nameEn: 'Buffalo meat, average', calories: 97, protein: 20.43, fat: 1.43, carbs: 0.93, tag: 'protein' },
  { name: 'Thịt trâu bắp', nameEn: 'Buffalo meat (shoulder)', calories: 115, protein: 21.91, fat: 3.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt trâu cổ', nameEn: 'Buffalo meat, neck', calories: 112, protein: 20.91, fat: 3.11, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt trâu đùi', nameEn: 'Buffalo meat, leg', calories: 112, protein: 21.21, fat: 3.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt trâu thăn', nameEn: 'Buffalo meat, lean (loin)', calories: 121, protein: 22.81, fat: 3.31, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt vịt', nameEn: 'Duck meat, average', calories: 267, protein: 17.81, fat: 21.81, carbs: 0.01, tag: 'protein' },
  { name: 'Bầu dục bò', nameEn: 'Beef, kidney', calories: 67, protein: 12.51, fat: 1.81, carbs: 0.31, tag: 'protein' },
  { name: 'Bầu dục lợn', nameEn: 'Pork, kidney', calories: 81, protein: 13.01, fat: 3.11, carbs: 0.31, tag: 'protein' },
  { name: 'Bì lợn', nameEn: 'Pork skin', calories: 118, protein: 23.31, fat: 2.71, carbs: 0.01, tag: 'protein' },
  { name: 'Chân giò lợn', nameEn: 'Pork, leg', calories: 230, protein: 15.71, fat: 18.61, carbs: 0.01, tag: 'protein' },
  { name: 'Dạ dày bò', nameEn: 'Stomach, beef', calories: 97, protein: 14.81, fat: 4.21, carbs: 0.01, tag: 'protein' },
  { name: 'Dạ dày lợn', nameEn: 'Stomach, hog', calories: 85, protein: 14.61, fat: 2.91, carbs: 0.01, tag: 'protein' },
  { name: 'Đầu bò', nameEn: 'Head beef (without tongue, brain, ears).', calories: 185, protein: 18.11, fat: 12.51, carbs: 0.01, tag: 'protein' },
  { name: 'Đầu lợn', nameEn: 'Hog, head', calories: 335, protein: 13.41, fat: 31.31, carbs: 0.01, tag: 'protein' },
  { name: 'Đuôi bò', nameEn: 'Beef, tail', calories: 137, protein: 19.71, fat: 6.51, carbs: 0.01, tag: 'protein' },
  { name: 'Đuôi lợn', nameEn: 'Hog, tail', calories: 467, protein: 10.81, fat: 47.11, carbs: 0.01, tag: 'protein' },
  { name: 'Gan bò', nameEn: 'Beef, liver', calories: 109, protein: 17.41, fat: 3.11, carbs: 3.01, tag: 'protein' },
  { name: 'Gan gà', nameEn: 'Chicken liver', calories: 111, protein: 18.21, fat: 3.41, carbs: 2.01, tag: 'protein' },
  { name: 'Gan lợn', nameEn: 'Pork liver', calories: 116, protein: 18.81, fat: 3.61, carbs: 2.01, tag: 'protein' },
  { name: 'Gan vịt', nameEn: 'Duck liver', calories: 122, protein: 17.11, fat: 4.71, carbs: 2.81, tag: 'protein' },
  { name: 'Gân chân bò', nameEn: 'M', calories: 124, protein: 30.21, fat: 0.31, carbs: 0.03, tag: 'protein' },
  { name: 'Lưỡi bò', nameEn: 'Beef tongue', calories: 164, protein: 13.61, fat: 12.11, carbs: 0.21, tag: 'protein' },
  { name: 'Lưỡi lợn', nameEn: 'Hog, tongue', calories: 178, protein: 14.21, fat: 12.81, carbs: 1.41, tag: 'protein' },
  { name: 'Lòng lợn (ruột già)', nameEn: 'Hog, intestine large raw', calories: 167, protein: 6.91, fat: 15.11, carbs: 0.81, tag: 'protein' },
  { name: 'Lòng lợn (ruột non)', nameEn: 'Hog intestine small raw without fat', calories: 44, protein: 7.21, fat: 1.31, carbs: 0.81, tag: 'protein' },
  { name: 'Mề gà', nameEn: 'Chicken gizzard', calories: 99, protein: 21.31, fat: 1.31, carbs: 0.61, tag: 'protein' },
  { name: 'Óc bò', nameEn: 'Brain beef', calories: 124, protein: 9.01, fat: 9.51, carbs: 0.51, tag: 'protein' },
  { name: 'óc lợn', nameEn: 'Hog brain', calories: 123, protein: 9.01, fat: 9.51, carbs: 0.41, tag: 'protein' },
  { name: 'Phổi bò', nameEn: 'Beef, lung', calories: 103, protein: 15.21, fat: 4.71, carbs: 0.01, tag: 'protein' },
  { name: 'Phổi lợn', nameEn: 'Hog lung, raw', calories: 92, protein: 14.81, fat: 3.61, carbs: 0.01, tag: 'protein' },
  { name: 'Sườn lợn', nameEn: 'Pork, ribs', calories: 187, protein: 17.91, fat: 12.81, carbs: 0.01, tag: 'protein' },
  { name: 'Tim bò', nameEn: 'Beef, heart', calories: 89, protein: 15.01, fat: 3.01, carbs: 0.61, tag: 'protein' },
  { name: 'Tim gà', nameEn: 'Chicken heart', calories: 114, protein: 16.01, fat: 5.51, carbs: 0.03, tag: 'protein' },
  { name: 'Tim lợn', nameEn: 'Hog heart', calories: 94, protein: 15.11, fat: 3.21, carbs: 1.23, tag: 'protein' },
  { name: 'Tiết bò', nameEn: 'Beef, blood', calories: 75, protein: 18.01, fat: 0.21, carbs: 0.41, tag: 'protein' },
  { name: 'Tiết lợn luộc', nameEn: 'Hog blood, boiled', calories: 44, protein: 10.71, fat: 0.11, carbs: 0.03, tag: 'protein' },
  { name: 'Tiết lợn sống', nameEn: 'Hog blood, raw', calories: 25, protein: 5.71, fat: 0.11, carbs: 0.21, tag: 'protein' },
  { name: 'Tủy xương bò', nameEn: 'Beef bone marrow', calories: 814, protein: 1.11, fat: 89.91, carbs: 0.01, tag: 'protein' },
  { name: 'Tủy xương lợn', nameEn: 'Hog, bone marrow', calories: 749, protein: 2.31, fat: 82.21, carbs: 0.01, tag: 'protein' },
  { name: 'Ba tê', nameEn: 'Pa tª', calories: 326, protein: 10.81, fat: 24.61, carbs: 15.41, tag: 'meal' },
  { name: 'Chả lợn', nameEn: 'Pork, mince fat meat grilled', calories: 517, protein: 10.81, fat: 50.41, carbs: 5.11, tag: 'protein' },
  { name: 'Chả quế lợn', nameEn: 'Pork, cinnamon mince grilled', calories: 416, protein: 16.21, fat: 39.01, carbs: 0.01, tag: 'protein' },
  { name: 'Dăm bông lợn', nameEn: 'Ham, pork', calories: 318, protein: 23.01, fat: 25.01, carbs: 0.31, tag: 'protein' },
  { name: 'Dồi lợn', nameEn: 'Blood mix-pudding with viscera in large intestine', calories: 114, protein: 12.41, fat: 7.11, carbs: 0.03, tag: 'meal' },
  { name: 'Giò bò', nameEn: 'Beef dumpling', calories: 357, protein: 13.81, fat: 33.51, carbs: 0.01, tag: 'protein' },
  { name: 'Giò lụa', nameEn: 'Pork, mince lean meat steamed', calories: 136, protein: 21.51, fat: 5.51, carbs: 0.03, tag: 'protein' },
  { name: 'Giò thủ lợn', nameEn: 'Pork, head meat, steamed', calories: 553, protein: 16.01, fat: 54.31, carbs: 0.03, tag: 'protein' },
  { name: 'Lạp xường', nameEn: 'Chinese sausage', calories: 585, protein: 20.81, fat: 55.01, carbs: 1.71, tag: 'protein' },
  { name: 'Nem chạo', nameEn: 'M', calories: 153, protein: 16.61, fat: 6.51, carbs: 6.91, tag: 'meal' },
  { name: 'Nem chua', nameEn: 'Pork mince, fermented', calories: 137, protein: 21.71, fat: 3.71, carbs: 4.31, tag: 'protein' },
  { name: 'Ruốc thịt lợn', nameEn: 'M', calories: 369, protein: 46.61, fat: 20.31, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt bò khô', nameEn: 'Dried beef', calories: 239, protein: 51.01, fat: 1.61, carbs: 5.21, tag: 'protein' },
  { name: 'Thịt trâu khô', nameEn: 'Buffalo meat, dried', calories: 226, protein: 50.41, fat: 2.71, carbs: 0.03, tag: 'protein' },
  { name: 'Xúc xích', nameEn: 'Pork sausage', calories: 535, protein: 27.21, fat: 47.41, carbs: 0.03, tag: 'protein' },
  { name: 'Bột cóc', nameEn: 'Toad meat powder', calories: 342, protein: 55.41, fat: 13.41, carbs: 0.01, tag: 'protein' },
  { name: 'Châu chấu', nameEn: 'Locust', calories: 130, protein: 24.31, fat: 3.61, carbs: 0.01, tag: 'protein' },
  { name: 'Ếch (thịt đùi)', nameEn: 'Frog', calories: 90, protein: 20.01, fat: 1.11, carbs: 0.01, tag: 'protein' },
  { name: 'Nhộng', nameEn: 'Silk worm', calories: 111, protein: 13.01, fat: 6.51, carbs: 0.01, tag: 'protein' },
  { name: 'Lòng gà (cả bộ)', nameEn: 'Chicken giblets', calories: 119, protein: 17.93, fat: 4.53, carbs: 1.83, tag: 'protein' },
  { name: 'Cá bống', nameEn: 'Goby, gudgeon', calories: 70, protein: 15.81, fat: 0.81, carbs: 0.01, tag: 'protein' },
  { name: 'Cá chày', nameEn: 'Pond fish', calories: 113, protein: 20.11, fat: 3.61, carbs: 0.01, tag: 'protein' },
  { name: 'Cá chép', nameEn: 'Carp', calories: 96, protein: 16.01, fat: 3.61, carbs: 0.01, tag: 'protein' },
  { name: 'Cá dưa', nameEn: 'Conger pike', calories: 115, protein: 17.61, fat: 5.01, carbs: 0.01, tag: 'protein' },
  { name: 'Cá dầu', nameEn: 'M', calories: 96, protein: 18.91, fat: 2.31, carbs: 0.01, tag: 'protein' },
  { name: 'Cá diếc', nameEn: 'Mullet, harder', calories: 87, protein: 17.71, fat: 1.81, carbs: 0.01, tag: 'protein' },
  { name: 'Cá đao', nameEn: 'Sawfish, wolfherring', calories: 94, protein: 18.31, fat: 2.31, carbs: 0.01, tag: 'protein' },
  { name: 'Cá đé', nameEn: 'Chinese herring', calories: 83, protein: 18.71, fat: 0.91, carbs: 0.01, tag: 'protein' },
  { name: 'Cá đối', nameEn: 'Mullet, gray mullet', calories: 108, protein: 19.51, fat: 3.31, carbs: 0.01, tag: 'protein' },
  { name: 'Cá đồng tiền', nameEn: 'Goby', calories: 98, protein: 20.11, fat: 2.01, carbs: 0.01, tag: 'protein' },
  { name: 'Cá hồi', nameEn: 'Salmon', calories: 136, protein: 22.01, fat: 5.31, carbs: 0.01, tag: 'protein' },
  { name: 'Cá khô (chim, thu, nụ, đé)', nameEn: 'Dried fish, miscellaneous', calories: 208, protein: 43.31, fat: 3.91, carbs: 0.01, tag: 'protein' },
  { name: 'Cá lác', nameEn: 'M', calories: 71, protein: 16.71, fat: 0.51, carbs: 0.01, tag: 'protein' },
  { name: 'Cá mì', nameEn: 'Hypophthalmichthys, chub, dory, tench bream', calories: 144, protein: 15.41, fat: 9.11, carbs: 0.01, tag: 'protein' },
  { name: 'Cá mòi', nameEn: 'Sardin', calories: 124, protein: 17.51, fat: 6.01, carbs: 0.01, tag: 'protein' },
  { name: 'Cá mỡ', nameEn: 'M', calories: 151, protein: 16.81, fat: 9.31, carbs: 0.01, tag: 'protein' },
  { name: 'Cá mối', nameEn: 'M', calories: 116, protein: 22.11, fat: 3.11, carbs: 0.01, tag: 'protein' },
  { name: 'Cá nạc', nameEn: 'Fish low fat', calories: 80, protein: 17.51, fat: 1.11, carbs: 0.01, tag: 'protein' },
  { name: 'Cá ngừ', nameEn: 'Flying fish, tuna', calories: 87, protein: 21.01, fat: 0.31, carbs: 0.01, tag: 'protein' },
  { name: 'Cá nục', nameEn: 'Scad, anchovy', calories: 111, protein: 20.21, fat: 3.31, carbs: 0.01, tag: 'protein' },
  { name: 'Cá phìn', nameEn: 'Goatfish, surmullet, red mullet', calories: 104, protein: 15.91, fat: 4.51, carbs: 0.01, tag: 'protein' },
  { name: 'Cá thờn bơn (cá bơn)', nameEn: 'Flounder, sole, turbot', calories: 73, protein: 17.41, fat: 0.41, carbs: 0.41, tag: 'protein' },
  { name: 'Cá thu', nameEn: 'Mackerel, codfish, kingfish', calories: 166, protein: 18.21, fat: 10.31, carbs: 0.01, tag: 'protein' },
  { name: 'Cá thu đao', nameEn: 'M', calories: 156, protein: 20.01, fat: 8.41, carbs: 0.01, tag: 'protein' },
  { name: 'Cá trạch (cá chạch)', nameEn: 'Loach', calories: 110, protein: 20.41, fat: 3.21, carbs: 0.01, tag: 'protein' },
  { name: 'Cá trắm cỏ', nameEn: 'Carp, amur', calories: 91, protein: 17.01, fat: 2.61, carbs: 0.01, tag: 'protein' },
  { name: 'Cá trê', nameEn: 'Catfish, silurus, sheatfish, hito', calories: 173, protein: 16.51, fat: 11.91, carbs: 0.01, tag: 'protein' },
  { name: 'Cá trích', nameEn: 'Herring', calories: 166, protein: 17.71, fat: 10.61, carbs: 0.01, tag: 'protein' },
  { name: 'Cua bể', nameEn: 'Crab, sea water', calories: 103, protein: 17.51, fat: 0.61, carbs: 7.01, tag: 'protein' },
  { name: 'Cua đồng', nameEn: 'Crab, fresh water', calories: 87, protein: 12.31, fat: 3.31, carbs: 2.01, tag: 'protein' },
  { name: 'Ghẹ', nameEn: 'Crab', calories: 54, protein: 11.91, fat: 0.71, carbs: 0.03, tag: 'protein' },
  { name: 'Hải sâm', nameEn: 'Sea slug, sea cucumber', calories: 90, protein: 21.51, fat: 0.31, carbs: 0.21, tag: 'protein' },
  { name: 'Hến', nameEn: 'Clam', calories: 45, protein: 4.51, fat: 0.71, carbs: 5.11, tag: 'protein' },
  { name: 'Lươn', nameEn: 'Eel, silver - pike', calories: 180, protein: 18.43, fat: 11.73, carbs: 0.23, tag: 'protein' },
  { name: 'Mực khô', nameEn: 'Dried cuttle fish, squid', calories: 291, protein: 60.11, fat: 4.51, carbs: 2.51, tag: 'protein' },
  { name: 'Mực tươi', nameEn: 'Cuttle fish, raw (Squid)', calories: 73, protein: 16.31, fat: 0.91, carbs: 0.03, tag: 'protein' },
  { name: 'ốc bươu', nameEn: 'Snail medium - size, edible', calories: 84, protein: 11.11, fat: 0.71, carbs: 8.31, tag: 'protein' },
  { name: 'ốc đá', nameEn: 'Marble snail, edible', calories: 63, protein: 11.21, fat: 0.31, carbs: 3.91, tag: 'protein' },
  { name: 'ốc nhồi', nameEn: 'Snail large, edible', calories: 84, protein: 11.91, fat: 0.71, carbs: 7.61, tag: 'protein' },
  { name: 'ốc vặn', nameEn: 'Helix', calories: 72, protein: 12.21, fat: 0.71, carbs: 4.31, tag: 'protein' },
  { name: 'Rạm (muối, đồ)', nameEn: 'Small sea - crab bicled, steamed', calories: 83, protein: 14.21, fat: 2.91, carbs: 0.03, tag: 'meal' },
  { name: 'Rạm tươi', nameEn: 'Small sea - crab', calories: 77, protein: 12.91, fat: 2.81, carbs: 0.03, tag: 'protein' },
  { name: 'Rươi', nameEn: 'Tylorhynchus sinensis', calories: 89, protein: 12.41, fat: 4.41, carbs: 0.03, tag: 'protein' },
  { name: 'Sò', nameEn: 'Oyster', calories: 78, protein: 9.51, fat: 2.31, carbs: 4.91, tag: 'protein' },
  { name: 'Tép gạo', nameEn: 'Tiny shrimp', calories: 58, protein: 11.71, fat: 1.21, carbs: 0.03, tag: 'protein' },
  { name: 'Tép khô', nameEn: 'Tiny shrimp, dried', calories: 269, protein: 59.81, fat: 3.01, carbs: 0.71, tag: 'protein' },
  { name: 'Tôm biển', nameEn: 'Sea shrimp, sea-water shrimp', calories: 82, protein: 17.61, fat: 0.91, carbs: 0.91, tag: 'protein' },
  { name: 'Tôm đồng', nameEn: 'Fresh-water shrimp', calories: 90, protein: 18.41, fat: 1.81, carbs: 0.03, tag: 'protein' },
  { name: 'Tôm khô', nameEn: 'Shrimp, dried', calories: 347, protein: 75.61, fat: 3.81, carbs: 2.51, tag: 'protein' },
  { name: 'Trai', nameEn: 'Manodonta', calories: 38, protein: 4.61, fat: 1.11, carbs: 2.51, tag: 'protein' },
  { name: 'Bánh phồng tôm rán', nameEn: 'Deep fried shrimp paste', calories: 676, protein: 1.61, fat: 59.21, carbs: 34.11, tag: 'junk' },
  { name: 'Bánh phồng tôm sống', nameEn: 'Shrimp paste', calories: 381, protein: 3.41, fat: 7.41, carbs: 75.31, tag: 'starch' },
  { name: 'Bột cá', nameEn: 'Fish flour with bones', calories: 323, protein: 71.21, fat: 2.91, carbs: 3.01, tag: 'protein' },
  { name: 'Ruốc cá quả', nameEn: 'Shredded snake-head fish, salted and dried', calories: 312, protein: 65.71, fat: 4.11, carbs: 3.01, tag: 'protein' },
  { name: 'Ruốc tôm', nameEn: 'Shredded shrimp, salted and dried', calories: 305, protein: 65.51, fat: 3.11, carbs: 3.71, tag: 'protein' },
  { name: 'Trứng gà', nameEn: 'Hen egg, raw, whole', calories: 166, protein: 14.81, fat: 11.61, carbs: 0.51, tag: 'protein' },
  { name: 'Lòng đỏ trứng gà', nameEn: 'Hen egg, yolk', calories: 327, protein: 13.61, fat: 29.81, carbs: 1.01, tag: 'protein' },
  { name: 'Lòng trắng trứng gà', nameEn: 'Hen egg, white', calories: 46, protein: 10.31, fat: 0.11, carbs: 1.01, tag: 'protein' },
  { name: 'Trứng vịt', nameEn: 'Duck egg, whole', calories: 184, protein: 13.01, fat: 14.21, carbs: 1.01, tag: 'protein' },
  { name: 'Lòng đỏ trứng vịt', nameEn: 'Duck egg, yolk', calories: 364, protein: 13.61, fat: 32.31, carbs: 4.81, tag: 'protein' },
  { name: 'Lòng trắng trứng vịt', nameEn: 'Duck egg, white', calories: 47, protein: 10.71, fat: 0.11, carbs: 0.83, tag: 'protein' },
  { name: 'Trứng chim cút', nameEn: 'Quail egg', calories: 154, protein: 13.13, fat: 11.13, carbs: 0.43, tag: 'protein' },
  { name: 'Fish roe', nameEn: 'Fish roe', calories: 171, protein: 20.51, fat: 9.91, carbs: 0.01, tag: 'protein' },
  { name: 'Trứng cá muối', nameEn: 'Fish caviar, black and red, granule', calories: 274, protein: 24.63, fat: 17.93, carbs: 3.53, tag: 'protein' },
  { name: 'Sữa bò tươi', nameEn: 'Milk cow, fresh (fluid)', calories: 74, protein: 3.91, fat: 4.41, carbs: 4.81, tag: 'dairy' },
  { name: 'Sữa dê tươi', nameEn: "Milk goat's, whole", calories: 69, protein: 3.51, fat: 4.11, carbs: 4.51, tag: 'dairy' },
  { name: 'Sữa mẹ (sữa người)', nameEn: 'Breast milk (Human milk, whole).', calories: 61, protein: 1.51, fat: 3.01, carbs: 7.01, tag: 'dairy' },
  { name: 'Sữa chua (từ sữa bò)', nameEn: 'Yogurt (whole milk)', calories: 61, protein: 3.31, fat: 3.71, carbs: 3.61, tag: 'dairy' },
  { name: 'Sữa chua vớt béo', nameEn: 'Yogurt, chocolate, nonfat milk', calories: 103, protein: 3.51, fat: 0.01, carbs: 22.31, tag: 'dairy' },
  { name: 'Sữa bột toàn phần', nameEn: 'Milk powder, whole', calories: 494, protein: 27.01, fat: 26.01, carbs: 38.01, tag: 'dairy' },
  { name: 'Sữa bột tách béo', nameEn: 'Skimmed milk powder', calories: 357, protein: 35.01, fat: 1.01, carbs: 52.01, tag: 'dairy' },
  { name: 'Sữa đặc có đường Việt Nam', nameEn: 'Milk condensed, sweetened', calories: 336, protein: 8.11, fat: 8.81, carbs: 56.01, tag: 'dairy' },
  { name: 'Pho mát', nameEn: 'Cheese (whole fat)', calories: 380, protein: 25.51, fat: 30.91, carbs: 0.01, tag: 'dairy' },
  { name: 'Chuối nước đường', nameEn: 'Banana, canned, sweetened', calories: 58, protein: 0.51, fat: 0.01, carbs: 13.91, tag: 'fruit' },
  { name: 'Dưa chuột hộp', nameEn: 'Cucumber (canned)', calories: 8, protein: 0.31, fat: 0.21, carbs: 1.21, tag: 'veggie' },
  { name: 'Dứa hộp', nameEn: 'Pineapple, canned, sweetened', calories: 53, protein: 0.41, fat: 0.11, carbs: 12.71, tag: 'fruit' },
  { name: 'Lạc chao dầu', nameEn: 'Peanut, oil fried', calories: 680, protein: 25.71, fat: 59.51, carbs: 10.31, tag: 'junk' },
  { name: 'Mắc coọc nước đường', nameEn: 'Pyrus pachis in syrup', calories: 56, protein: 0.21, fat: 0.01, carbs: 13.71, tag: 'fruit' },
  { name: 'Mận nước đường', nameEn: 'Plum, canned, sweetened', calories: 64, protein: 0.41, fat: 0.11, carbs: 15.41, tag: 'fruit' },
  { name: 'Mứt bí ngô', nameEn: 'Dried preserved squash', calories: 198, protein: 0.51, fat: 0.01, carbs: 49.11, tag: 'junk' },
  { name: 'Mứt cam có vỏ', nameEn: 'Orange marmalade, jellies', calories: 218, protein: 0.41, fat: 0.01, carbs: 54.21, tag: 'junk' },
  { name: 'Mứt chuối', nameEn: 'Banana jam', calories: 218, protein: 0.71, fat: 0.01, carbs: 53.91, tag: 'junk' },
  { name: 'Mứt dứa', nameEn: 'Pineapple jam', calories: 208, protein: 0.51, fat: 0.01, carbs: 51.51, tag: 'junk' },
  { name: 'Mứt đu đủ', nameEn: 'Papaya jam', calories: 178, protein: 0.41, fat: 0.01, carbs: 44.11, tag: 'junk' },
  { name: 'Nhãn nước đường', nameEn: 'Longan, canned, sweetened', calories: 62, protein: 0.51, fat: 0.01, carbs: 15.01, tag: 'fruit' },
  { name: 'Nước dứa hộp', nameEn: 'Pineapple juice', calories: 53, protein: 0.41, fat: 0.11, carbs: 12.61, tag: 'softdrink' },
  { name: 'Vải nước đường', nameEn: 'Litchi, canned, sweetened', calories: 60, protein: 0.41, fat: 0.01, carbs: 14.71, tag: 'fruit' },
  { name: 'Cá thu hộp', nameEn: 'Mackerel, canned', calories: 207, protein: 24.81, fat: 12.01, carbs: 0.01, tag: 'protein' },
  { name: 'Cá trích hộp', nameEn: 'Herring, canned', calories: 233, protein: 22.31, fat: 14.41, carbs: 3.51, tag: 'protein' },
  { name: 'Thịt bò hộp', nameEn: 'Beef, canned', calories: 251, protein: 16.41, fat: 20.61, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt gà hộp', nameEn: 'Chicken, canned', calories: 273, protein: 17.01, fat: 22.81, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt lợn hộp', nameEn: 'Pork, canned', calories: 344, protein: 17.31, fat: 29.31, carbs: 2.71, tag: 'protein' },
  { name: 'Thịt lợn, thịt bò xay hộp', nameEn: 'Pork and beef, minced canned', calories: 244, protein: 16.01, fat: 20.01, carbs: 0.01, tag: 'protein' },
  { name: 'Thịt vịt hầm', nameEn: 'Duck, stewed meat', calories: 224, protein: 19.61, fat: 16.21, carbs: 0.01, tag: 'meal' },
  { name: 'Bánh bích cốt', nameEn: 'Whole wheat rusk', calories: 346, protein: 12.31, fat: 1.31, carbs: 71.31, tag: 'junk' },
  { name: 'Bánh bích quy', nameEn: 'Biscuits', calories: 376, protein: 8.81, fat: 4.51, carbs: 75.11, tag: 'junk' },
  { name: 'Bánh chả', nameEn: 'Sweet meat pie in lumps', calories: 395, protein: 3.41, fat: 6.61, carbs: 80.51, tag: 'junk' },
  { name: 'Bánh con cá', nameEn: 'Small biscuits, fish figured', calories: 368, protein: 7.51, fat: 2.21, carbs: 79.61, tag: 'junk' },
  { name: 'Bánh đậu xanh', nameEn: 'Mungbean cake', calories: 416, protein: 15.61, fat: 11.51, carbs: 62.41, tag: 'junk' },
  { name: 'Bánh kem xốp', nameEn: 'Wafers filled', calories: 492, protein: 8.31, fat: 24.01, carbs: 60.71, tag: 'junk' },
  { name: 'Bánh khảo chay', nameEn: 'Rice cake, plain', calories: 376, protein: 3.21, fat: 0.31, carbs: 90.21, tag: 'junk' },
  { name: 'Bánh quế', nameEn: 'Cinnamon waffle (roll)', calories: 435, protein: 8.31, fat: 10.71, carbs: 76.41, tag: 'junk' },
  { name: 'Bánh sô cô la', nameEn: 'Chocolate, filled', calories: 449, protein: 3.91, fat: 17.61, carbs: 68.81, tag: 'junk' },
  { name: 'Bánh thỏi sô cô la', nameEn: 'Chocolate, sweet', calories: 543, protein: 4.91, fat: 30.41, carbs: 62.51, tag: 'junk' },
  { name: 'Bánh trứng nhện', nameEn: 'Small biscuit', calories: 369, protein: 9.61, fat: 3.71, carbs: 74.21, tag: 'junk' },
  { name: 'Bột ca cao', nameEn: 'Cocoa powder', calories: 414, protein: 19.61, fat: 13.71, carbs: 53.01, tag: 'junk' },
  { name: 'Đường cát', nameEn: 'Refined sugar', calories: 390, protein: 0.01, fat: 0.01, carbs: 97.41, tag: 'condiment' },
  { name: 'Đường kính', nameEn: 'Granulated sugar', calories: 397, protein: 0.01, fat: 0.01, carbs: 99.31, tag: 'condiment' },
  { name: 'Kẹo bơ cứng', nameEn: 'Toffee, sweets', calories: 448, protein: 2.11, fat: 17.21, carbs: 71.11, tag: 'junk' },
  { name: 'Kẹo cà phê', nameEn: 'Coffee sweets', calories: 378, protein: 0.01, fat: 1.31, carbs: 91.51, tag: 'junk' },
  { name: 'Kẹo cam chanh', nameEn: 'Sweets, caramel with citron, orange aroma', calories: 377, protein: 0.01, fat: 0.51, carbs: 93.11, tag: 'junk' },
  { name: 'Kẹo dừa mềm', nameEn: 'Sweets with coconut aroma', calories: 415, protein: 0.61, fat: 12.21, carbs: 75.61, tag: 'junk' },
  { name: 'Kẹo dứa mềm', nameEn: 'Pineapple sweets candy', calories: 415, protein: 0.61, fat: 12.21, carbs: 75.61, tag: 'junk' },
  { name: 'Kẹo lạc', nameEn: 'Peanut candy', calories: 449, protein: 10.31, fat: 16.51, carbs: 64.81, tag: 'junk' },
  { name: 'Kẹo Pastille (kẹo ngậm bạc hà)', nameEn: 'Menthol pastille', calories: 356, protein: 5.21, fat: 0.01, carbs: 83.81, tag: 'junk' },
  { name: 'Kẹo sô cô la', nameEn: 'Sweets with chocolate', calories: 388, protein: 1.61, fat: 4.61, carbs: 85.11, tag: 'junk' },
  { name: 'Kẹo sữa', nameEn: 'Sweets with milk', calories: 390, protein: 2.91, fat: 5.21, carbs: 83.01, tag: 'junk' },
  { name: 'Kẹo vừng viên', nameEn: 'Sesame candy', calories: 417, protein: 2.81, fat: 6.91, carbs: 85.91, tag: 'junk' },
  { name: 'Mạch nha', nameEn: 'Malt', calories: 331, protein: 0.21, fat: 0.01, carbs: 82.51, tag: 'junk' },
  { name: 'Mật ong', nameEn: 'Honey', calories: 327, protein: 0.41, fat: 0.01, carbs: 81.31, tag: 'condiment' },
  { name: 'Mứt lạc', nameEn: 'Peanut sugar (Jam)', calories: 431, protein: 5.41, fat: 8.61, carbs: 82.91, tag: 'junk' },
  { name: 'Cary bột', nameEn: 'Cari powder (Mix, turmeric, red pepper and other spices)', calories: 283, protein: 8.21, fat: 7.31, carbs: 46.01, tag: 'condiment' },
  { name: 'Gừng khô (bột)', nameEn: 'Ginger root, dried powder', calories: 323, protein: 9.11, fat: 5.91, carbs: 58.31, tag: 'condiment' },
  { name: 'Gừng tươi', nameEn: 'Ginger root, fresh', calories: 29, protein: 0.41, fat: 0.83, carbs: 5.11, tag: 'condiment' },
  { name: 'Hạt tiêu', nameEn: 'Peppercorn, seeds', calories: 231, protein: 7.01, fat: 7.41, carbs: 34.11, tag: 'condiment' },
  { name: 'Muối', nameEn: 'Table salt', calories: 0, protein: 0.01, fat: 0.01, carbs: 0.01, tag: 'condiment' },
  { name: 'Nghệ khô, bột', nameEn: 'Turmeric rhizome, dried powder', calories: 295, protein: 7.83, fat: 9.93, carbs: 43.83, tag: 'condiment' },
  { name: 'Nghệ tươi', nameEn: 'Turmeric, rhizome, fresh', calories: 25, protein: 1.16, fat: 0.36, carbs: 4.46, tag: 'condiment' },
  { name: 'Ớt khô bột', nameEn: 'Red pepper, dried powder', calories: 227, protein: 15.61, fat: 4.21, carbs: 31.81, tag: 'condiment' },
  { name: 'Riềng', nameEn: 'Alpinia root, fresh', calories: 26, protein: 0.31, fat: 0, carbs: 2.51, tag: 'condiment' },
  { name: 'Xì dầu', nameEn: 'Soybean sauce', calories: 65, protein: 10.51, fat: 0.13, carbs: 5.63, tag: 'condiment' },
  { name: 'Mắm tôm đặc', nameEn: 'Shrimp sauce concentrate', calories: 73, protein: 14.81, fat: 1.51, carbs: 0.03, tag: 'condiment' },
  { name: 'Mắm tôm loãng', nameEn: 'Shrimp sauce, diluted', calories: 44, protein: 7.01, fat: 0.81, carbs: 2.11, tag: 'condiment' },
  { name: 'Mắm tép chua', nameEn: 'Tiny shrimp, sour sauce', calories: 68, protein: 8.71, fat: 1.21, carbs: 5.51, tag: 'condiment' },
  { name: 'Nước mắm cá (loại đặc biệt)', nameEn: 'Fish - sauce (super quality).', calories: 60, protein: 15.01, fat: 0.01, carbs: 0.01, tag: 'condiment' },
  { name: 'Nước mắm loại I', nameEn: 'Fish sauce, grade I', calories: 28, protein: 7.11, fat: 0.001, carbs: 0.01, tag: 'condiment' },
  { name: 'Nước mắm loại II', nameEn: 'Fish sauce, grade II', calories: 21, protein: 5.21, fat: 0.01, carbs: 0.01, tag: 'condiment' },
  { name: 'Nước mắm cá', nameEn: 'Fish sauce, ready-to-serve', calories: 35, protein: 5.11, fat: 0.011, carbs: 3.61, tag: 'condiment' },
  { name: 'Nước mắm cô', nameEn: 'Fish sauce, concentrated', calories: 131, protein: 32.81, fat: 0.03, carbs: 0.03, tag: 'condiment' },
  { name: 'Tương ngô', nameEn: 'Soybean sauce with rice and maize', calories: 75, protein: 3.91, fat: 0.11, carbs: 14.51, tag: 'condiment' },
  { name: 'Tương nếp', nameEn: 'Soybean sauce with glutinous rice', calories: 86, protein: 4.31, fat: 0.71, carbs: 15.71, tag: 'condiment' },
  { name: 'Tương ớt', nameEn: 'Red pepper sauce concentrate', calories: 37, protein: 0.51, fat: 0.51, carbs: 7.61, tag: 'condiment' },
  { name: 'Bia (cồn: 4,5 g)', nameEn: 'Beer light (4,5 % Alcohol)', calories: 11, protein: 0.51, fat: 0.03, carbs: 2.31, tag: 'alcohol' },
  { name: 'Cô nhắc (cồn 32 g)', nameEn: 'Cognac', calories: 0, protein: 0.03, fat: 0.03, carbs: 0.03, tag: 'alcohol' },
  { name: 'Cốc tai (cồn 13 g)', nameEn: 'Cocktail, vermouth sweet', calories: 63, protein: 0.01, fat: 0.03, carbs: 15.71, tag: 'alcohol' },
  { name: 'Coca cola', nameEn: 'Coca Cola', calories: 42, protein: 0.01, fat: 0.03, carbs: 10.41, tag: 'softdrink' },
  { name: 'Nước cam tươi', nameEn: 'Orange juice, fresh', calories: 23, protein: 0.71, fat: 0.23, carbs: 4.51, tag: 'beverage' },
  { name: 'Nước dừa non tươi', nameEn: 'Coconut milk, immature', calories: 21, protein: 0.41, fat: 0.03, carbs: 4.81, tag: 'beverage' },
  { name: 'Nước ép càchua', nameEn: 'Tomato juice', calories: 19, protein: 0.81, fat: 0.61, carbs: 2.61, tag: 'beverage' },
  { name: 'Nước khoáng', nameEn: 'Mineral water', calories: 0, protein: 0.03, fat: 0.03, carbs: 0.03, tag: 'beverage' },
  { name: 'Nước quít tươi', nameEn: 'Mandarins juice (fresh)', calories: 24, protein: 0.41, fat: 0.23, carbs: 5.11, tag: 'beverage' },
  { name: 'Rượu cam, chanh (cồn 24,2 g)', nameEn: 'Liqueur, orange flavor', calories: 0, protein: 0.03, fat: 0.03, carbs: 0.01, tag: 'alcohol' },
  { name: 'Rượu nếp (80g/ 24 ml) (cồn 5 g)', nameEn: 'Rice glutinous (Alcohol fermentation rice 80 g water 24 ml)', calories: 167, protein: 4.01, fat: 0.03, carbs: 37.71, tag: 'alcohol' },
  { name: 'Rượu trắng (cồn 39 g)', nameEn: 'Vodka', calories: 273, protein: 0, fat: 0.03, carbs: 0, tag: 'alcohol' },
  { name: 'Rượu vang đỏ (cồn 9,5 g)', nameEn: 'Red wine', calories: 9, protein: 0.21, fat: 0.03, carbs: 2.01, tag: 'alcohol' },
  { name: 'Rượu vang trắng (cồn 9,5 g)', nameEn: 'White wine', calories: 1, protein: 0.15, fat: 0.05, carbs: 0.25, tag: 'alcohol' },
  { name: 'Rượu vang trắng ngọt (cồn 10.2 g)', nameEn: 'White wine, sweet', calories: 24, protein: 0.25, fat: 0.05, carbs: 5.95, tag: 'alcohol' },
  { name: 'Rượu Whisky (cồn 35,2 g)', nameEn: 'Whisky liqueur', calories: 0, protein: 0.01, fat: 0.01, carbs: 0.01, tag: 'alcohol' },

  // ─── Đồ uống: trà, nước ép, sinh tố, giải khát (per 100ml) ───
  { name: 'Trà đá (ko đường)', nameEn: 'Iced tea (no sugar)', calories: 1, protein: 0, fat: 0, carbs: 0.3, tag: 'beverage' },
  { name: 'Trà xanh (ko đường)', nameEn: 'Green tea (no sugar)', calories: 1, protein: 0, fat: 0, carbs: 0.2, tag: 'beverage' },
  { name: 'Trà ô long (ko đường)', nameEn: 'Oolong tea (no sugar)', calories: 1, protein: 0, fat: 0, carbs: 0.3, tag: 'beverage' },
  { name: 'Trà chanh', nameEn: 'Lemon tea (sweetened)', calories: 28, protein: 0.1, fat: 0, carbs: 7, tag: 'beverage' },
  { name: 'Trà tắc (trà quất)', nameEn: 'Kumquat tea (sweetened)', calories: 30, protein: 0.1, fat: 0, carbs: 7.5, tag: 'beverage' },
  { name: 'Trà đào', nameEn: 'Peach tea (sweetened)', calories: 40, protein: 0.1, fat: 0, carbs: 10, tag: 'beverage' },
  { name: 'Trà sữa trân châu', nameEn: 'Bubble milk tea', calories: 90, protein: 1, fat: 2.5, carbs: 16, tag: 'beverage' },
  { name: 'Trà sữa (ko trân châu)', nameEn: 'Milk tea (no pearls)', calories: 70, protein: 1.2, fat: 2.2, carbs: 11, tag: 'beverage' },
  { name: 'Nước mía', nameEn: 'Sugarcane juice', calories: 55, protein: 0.1, fat: 0.1, carbs: 14, tag: 'beverage' },
  { name: 'Nước sâm (sâm bí đao)', nameEn: 'Winter melon herbal tea', calories: 30, protein: 0.1, fat: 0, carbs: 7.5, tag: 'beverage' },
  { name: 'Nước chanh (có đường)', nameEn: 'Lemonade (sweetened)', calories: 30, protein: 0.1, fat: 0, carbs: 7.6, tag: 'beverage' },
  { name: 'Sinh tố bơ', nameEn: 'Avocado smoothie', calories: 130, protein: 1.8, fat: 7, carbs: 15, tag: 'beverage' },
  { name: 'Sinh tố xoài', nameEn: 'Mango smoothie', calories: 90, protein: 1.2, fat: 1.5, carbs: 18, tag: 'beverage' },
  { name: 'Nước ép ổi', nameEn: 'Guava juice', calories: 45, protein: 0.6, fat: 0.2, carbs: 10.5, tag: 'beverage' },
  { name: 'Nước ép táo', nameEn: 'Apple juice', calories: 46, protein: 0.1, fat: 0.1, carbs: 11.3, tag: 'beverage' },
  { name: 'Nước ép cà rốt', nameEn: 'Carrot juice', calories: 40, protein: 0.9, fat: 0.1, carbs: 9.3, tag: 'beverage' },
  { name: 'Nước ép dưa hấu', nameEn: 'Watermelon juice', calories: 30, protein: 0.6, fat: 0.1, carbs: 7.5, tag: 'beverage' },

  // ─── Nước ngọt có ga & nước tăng lực (per 100ml) ───
  { name: 'Pepsi', nameEn: 'Pepsi', calories: 43, protein: 0, fat: 0, carbs: 11, tag: 'softdrink' },
  { name: '7Up', nameEn: '7Up', calories: 40, protein: 0, fat: 0, carbs: 10.2, tag: 'softdrink' },
  { name: 'Sprite', nameEn: 'Sprite', calories: 39, protein: 0, fat: 0, carbs: 10, tag: 'softdrink' },
  { name: 'Fanta cam', nameEn: 'Fanta Orange', calories: 48, protein: 0, fat: 0, carbs: 12, tag: 'softdrink' },
  { name: 'Mirinda', nameEn: 'Mirinda', calories: 47, protein: 0, fat: 0, carbs: 11.8, tag: 'softdrink' },
  { name: 'Coca Cola Zero', nameEn: 'Coca Cola Zero', calories: 0.3, protein: 0, fat: 0, carbs: 0, tag: 'softdrink' },
  { name: 'Nước tăng lực Sting', nameEn: 'Sting Energy Drink', calories: 51, protein: 0, fat: 0, carbs: 13, tag: 'softdrink' },
  { name: 'Red Bull', nameEn: 'Red Bull', calories: 45, protein: 0, fat: 0, carbs: 11, tag: 'softdrink' },
  { name: 'Monster Energy', nameEn: 'Monster Energy', calories: 47, protein: 0, fat: 0, carbs: 11, tag: 'softdrink' },
  { name: 'Number 1', nameEn: 'Number 1 Energy Drink', calories: 50, protein: 0, fat: 0, carbs: 12.5, tag: 'softdrink' },
  { name: 'Trà xanh 0 độ (đóng chai)', nameEn: 'Bottled green tea (0 Do)', calories: 24, protein: 0, fat: 0, carbs: 6, tag: 'softdrink' },
  { name: 'C2 (trà đóng chai)', nameEn: 'C2 bottled tea', calories: 22, protein: 0, fat: 0, carbs: 5.5, tag: 'softdrink' },

  // ─── Trái cây bổ sung ───
  { name: 'Cam (cả quả)', nameEn: 'Orange, whole', calories: 47, protein: 0.9, fat: 0.1, carbs: 11.8, fiber: 2.4, tag: 'fruit' },
  { name: 'Chanh', nameEn: 'Lime / Lemon', calories: 29, protein: 1.1, fat: 0.3, carbs: 9.3, fiber: 2.8, tag: 'fruit' },
  { name: 'Mít', nameEn: 'Jackfruit', calories: 95, protein: 1.7, fat: 0.6, carbs: 23.2, fiber: 1.5, tag: 'fruit' },
  { name: 'Măng cụt', nameEn: 'Mangosteen', calories: 73, protein: 0.4, fat: 0.6, carbs: 18, fiber: 1.8, tag: 'fruit' },
  { name: 'Hồng xiêm (Sapôchê)', nameEn: 'Sapodilla', calories: 83, protein: 0.4, fat: 1.1, carbs: 20, fiber: 5.3, tag: 'fruit' },
  { name: 'Vú sữa', nameEn: 'Star apple', calories: 67, protein: 1.5, fat: 1.2, carbs: 14.6, fiber: 3.3, tag: 'fruit' },
  { name: 'Chanh leo (Chanh dây)', nameEn: 'Passion fruit', calories: 97, protein: 2.2, fat: 0.7, carbs: 23.4, fiber: 10.4, tag: 'fruit' },
  { name: 'Roi (Mận miền Nam)', nameEn: 'Water apple / Rose apple', calories: 25, protein: 0.6, fat: 0.3, carbs: 5.7, fiber: 1.5, tag: 'fruit' },
  { name: 'Dưa lê', nameEn: 'Honeydew melon', calories: 36, protein: 0.5, fat: 0.1, carbs: 9.1, fiber: 0.8, tag: 'fruit' },
  { name: 'Dưa gang', nameEn: 'Vietnamese melon', calories: 16, protein: 0.6, fat: 0.1, carbs: 3.5, fiber: 0.5, tag: 'fruit' },
  { name: 'Me chín', nameEn: 'Tamarind, ripe', calories: 239, protein: 2.8, fat: 0.6, carbs: 62.5, fiber: 5.1, tag: 'fruit' },
  { name: 'Hồng (quả hồng)', nameEn: 'Persimmon', calories: 70, protein: 0.6, fat: 0.2, carbs: 18.6, fiber: 3.6, tag: 'fruit' },
  { name: 'Đào', nameEn: 'Peach', calories: 39, protein: 0.9, fat: 0.3, carbs: 9.5, fiber: 1.5, tag: 'fruit' },
  { name: 'Mơ', nameEn: 'Apricot', calories: 48, protein: 1.4, fat: 0.4, carbs: 11, fiber: 2, tag: 'fruit' },
  { name: 'Cherry (Anh đào)', nameEn: 'Cherry', calories: 63, protein: 1.1, fat: 0.2, carbs: 16, fiber: 2.1, tag: 'fruit' },
  { name: 'Việt quất (Blueberry)', nameEn: 'Blueberry', calories: 57, protein: 0.7, fat: 0.3, carbs: 14.5, fiber: 2.4, tag: 'fruit' },
  { name: 'Lựu', nameEn: 'Pomegranate', calories: 83, protein: 1.7, fat: 1.2, carbs: 18.7, fiber: 4, tag: 'fruit' },
  { name: 'Sơ ri', nameEn: 'Acerola cherry', calories: 32, protein: 0.4, fat: 0.3, carbs: 7.7, fiber: 1.1, tag: 'fruit' },
  { name: 'Dâu tằm', nameEn: 'Mulberry', calories: 43, protein: 1.4, fat: 0.4, carbs: 9.8, fiber: 1.7, tag: 'fruit' },
  { name: 'Sung', nameEn: 'Fig', calories: 74, protein: 0.8, fat: 0.3, carbs: 19, fiber: 2.9, tag: 'fruit' },
  { name: 'Bòn bon (Lòn bon)', nameEn: 'Langsat / Lanzones', calories: 57, protein: 0.8, fat: 0.2, carbs: 14.2, fiber: 2.3, tag: 'fruit' },

  // ─── Sữa & chế phẩm bổ sung (sữa chua Hy Lạp, phô mai, sữa hạt) ───
  { name: 'Sữa chua Hy Lạp (ko đường)', nameEn: 'Greek yogurt, plain', calories: 59, protein: 10, fat: 0.4, carbs: 3.6, tag: 'dairy' },
  { name: 'Sữa chua Hy Lạp (có đường)', nameEn: 'Greek yogurt, sweetened', calories: 97, protein: 9, fat: 2, carbs: 9, tag: 'dairy' },
  { name: 'Cream cheese (Phô mai kem)', nameEn: 'Cream cheese', calories: 342, protein: 6, fat: 34, carbs: 4, tag: 'dairy' },
  { name: 'Phô mai Parmesan', nameEn: 'Parmesan cheese', calories: 431, protein: 38, fat: 29, carbs: 4.1, tag: 'dairy' },
  { name: 'Phô mai Feta', nameEn: 'Feta cheese', calories: 264, protein: 14, fat: 21, carbs: 4, tag: 'dairy' },
  { name: 'Váng sữa', nameEn: 'Milk curd dessert (váng sữa)', calories: 150, protein: 3, fat: 9, carbs: 14, tag: 'dairy' },
  { name: 'Kem tươi (Whipping cream)', nameEn: 'Whipping cream', calories: 340, protein: 2.1, fat: 36, carbs: 2.8, tag: 'dairy' },
  { name: 'Kem ăn (vani)', nameEn: 'Ice cream, vanilla', calories: 207, protein: 3.5, fat: 11, carbs: 24, tag: 'dairy' },
  { name: 'Sữa hạnh nhân (ko đường)', nameEn: 'Almond milk, unsweetened', calories: 15, protein: 0.6, fat: 1.2, carbs: 0.6, tag: 'dairy' },
  { name: 'Sữa yến mạch', nameEn: 'Oat milk', calories: 47, protein: 0.8, fat: 1.5, carbs: 7, tag: 'dairy' },
  { name: 'Sữa óc chó', nameEn: 'Walnut milk', calories: 40, protein: 1, fat: 1.5, carbs: 5.5, tag: 'dairy' },

  // ─── Hạt & chất béo bổ sung ───
  { name: 'Óc chó (đã bỏ vỏ)', nameEn: 'Walnuts (shelled)', calories: 654, protein: 15.2, fat: 65.2, carbs: 13.7, tag: 'fat' },
  { name: 'Hạt chia', nameEn: 'Chia seeds', calories: 486, protein: 16.5, fat: 30.7, carbs: 42.1, fiber: 34.4, tag: 'fat' },
  { name: 'Hạt lanh', nameEn: 'Flaxseed', calories: 534, protein: 18.3, fat: 42.2, carbs: 28.9, fiber: 27.3, tag: 'fat' },
  { name: 'Quả ô liu', nameEn: 'Olives', calories: 115, protein: 0.8, fat: 10.7, carbs: 6.3, fiber: 3.2, tag: 'fat' },
  { name: 'Bơ hạnh nhân', nameEn: 'Almond butter', calories: 614, protein: 21, fat: 56, carbs: 19, tag: 'fat' },
  { name: 'Dầu bơ', nameEn: 'Avocado oil', calories: 884, protein: 0, fat: 100, carbs: 0, tag: 'fat' },
  { name: 'Dầu hạt cải (Canola)', nameEn: 'Canola oil', calories: 884, protein: 0, fat: 100, carbs: 0, tag: 'fat' },
  { name: 'Dầu hướng dương', nameEn: 'Sunflower oil', calories: 884, protein: 0, fat: 100, carbs: 0, tag: 'fat' },

  // ─── Tinh bột eat-clean bổ sung ───
  { name: 'Diêm mạch (Quinoa) chín', nameEn: 'Quinoa, cooked', calories: 120, protein: 4.4, fat: 1.9, carbs: 21.3, fiber: 2.8, tag: 'starch' },
  { name: 'Granola', nameEn: 'Granola', calories: 471, protein: 10, fat: 20, carbs: 64, fiber: 7, tag: 'starch' },
  { name: 'Khoai lang nướng', nameEn: 'Baked sweet potato', calories: 90, protein: 2, fat: 0.2, carbs: 20.7, fiber: 3.3, tag: 'starch' },
  { name: 'Bánh gạo lứt', nameEn: 'Brown rice cake', calories: 387, protein: 8.2, fat: 2.8, carbs: 81.5, fiber: 4.2, tag: 'starch' },
  { name: 'Couscous (chín)', nameEn: 'Couscous, cooked', calories: 112, protein: 3.8, fat: 0.2, carbs: 23.2, fiber: 1.4, tag: 'starch' },
];
